// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_track_template_v1.proto

#include "video_track_template_v1.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace mergenvision {
namespace video {
namespace v1 {
PROTOBUF_CONSTEXPR TrackTemplateBundle::TrackTemplateBundle(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.templates_)*/{}
  , /*decltype(_impl_.job_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.video_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.model_version_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.preprocess_version_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.config_version_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sequence_no_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TrackTemplateBundleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TrackTemplateBundleDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TrackTemplateBundleDefaultTypeInternal() {}
  union {
    TrackTemplateBundle _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TrackTemplateBundleDefaultTypeInternal _TrackTemplateBundle_default_instance_;
PROTOBUF_CONSTEXPR RawTrackTemplate::RawTrackTemplate(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.template_embedding_)*/{}
  , /*decltype(_impl_.raw_track_key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.representative_crop_relative_key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.no_crop_reason_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.first_pts_ns_)*/int64_t{0}
  , /*decltype(_impl_.last_pts_ns_)*/int64_t{0}
  , /*decltype(_impl_.observation_count_)*/int64_t{0}
  , /*decltype(_impl_.eligible_observation_count_)*/int64_t{0}
  , /*decltype(_impl_.template_quality_)*/0
  , /*decltype(_impl_.representative_x_)*/0
  , /*decltype(_impl_.representative_y_)*/0
  , /*decltype(_impl_.representative_width_)*/0
  , /*decltype(_impl_.representative_pts_ns_)*/int64_t{0}
  , /*decltype(_impl_.representative_height_)*/0
  , /*decltype(_impl_.representative_ordinal_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RawTrackTemplateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RawTrackTemplateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RawTrackTemplateDefaultTypeInternal() {}
  union {
    RawTrackTemplate _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RawTrackTemplateDefaultTypeInternal _RawTrackTemplate_default_instance_;
PROTOBUF_CONSTEXPR TrackTemplateFooter::TrackTemplateFooter(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.job_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sequence_no_)*/int64_t{0}
  , /*decltype(_impl_.template_count_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TrackTemplateFooterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TrackTemplateFooterDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TrackTemplateFooterDefaultTypeInternal() {}
  union {
    TrackTemplateFooter _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TrackTemplateFooterDefaultTypeInternal _TrackTemplateFooter_default_instance_;
}  // namespace v1
}  // namespace video
}  // namespace mergenvision
static ::_pb::Metadata file_level_metadata_video_5ftrack_5ftemplate_5fv1_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_video_5ftrack_5ftemplate_5fv1_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_video_5ftrack_5ftemplate_5fv1_2eproto = nullptr;

const uint32_t TableStruct_video_5ftrack_5ftemplate_5fv1_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::TrackTemplateBundle, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::TrackTemplateBundle, _impl_.job_id_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::TrackTemplateBundle, _impl_.video_id_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::TrackTemplateBundle, _impl_.sequence_no_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::TrackTemplateBundle, _impl_.model_version_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::TrackTemplateBundle, _impl_.preprocess_version_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::TrackTemplateBundle, _impl_.config_version_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::TrackTemplateBundle, _impl_.templates_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _impl_.raw_track_key_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _impl_.first_pts_ns_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _impl_.last_pts_ns_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _impl_.observation_count_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _impl_.eligible_observation_count_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _impl_.template_embedding_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _impl_.template_quality_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _impl_.representative_crop_relative_key_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _impl_.representative_x_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _impl_.representative_y_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _impl_.representative_width_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _impl_.representative_height_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _impl_.representative_pts_ns_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _impl_.representative_ordinal_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::RawTrackTemplate, _impl_.no_crop_reason_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::TrackTemplateFooter, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::TrackTemplateFooter, _impl_.job_id_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::TrackTemplateFooter, _impl_.sequence_no_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::TrackTemplateFooter, _impl_.template_count_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::mergenvision::video::v1::TrackTemplateBundle)},
  { 13, -1, -1, sizeof(::mergenvision::video::v1::RawTrackTemplate)},
  { 34, -1, -1, sizeof(::mergenvision::video::v1::TrackTemplateFooter)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::mergenvision::video::v1::_TrackTemplateBundle_default_instance_._instance,
  &::mergenvision::video::v1::_RawTrackTemplate_default_instance_._instance,
  &::mergenvision::video::v1::_TrackTemplateFooter_default_instance_._instance,
};

const char descriptor_table_protodef_video_5ftrack_5ftemplate_5fv1_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035video_track_template_v1.proto\022\025mergenv"
  "ision.video.v1\"\323\001\n\023TrackTemplateBundle\022\016"
  "\n\006job_id\030\001 \001(\t\022\020\n\010video_id\030\002 \001(\t\022\023\n\013sequ"
  "ence_no\030\003 \001(\003\022\025\n\rmodel_version\030\004 \001(\t\022\032\n\022"
  "preprocess_version\030\005 \001(\t\022\026\n\016config_versi"
  "on\030\006 \001(\t\022:\n\ttemplates\030\007 \003(\0132\'.mergenvisi"
  "on.video.v1.RawTrackTemplate\"\273\003\n\020RawTrac"
  "kTemplate\022\025\n\rraw_track_key\030\001 \001(\t\022\024\n\014firs"
  "t_pts_ns\030\002 \001(\003\022\023\n\013last_pts_ns\030\003 \001(\003\022\031\n\021o"
  "bservation_count\030\004 \001(\003\022\"\n\032eligible_obser"
  "vation_count\030\005 \001(\003\022\032\n\022template_embedding"
  "\030\006 \003(\002\022\030\n\020template_quality\030\007 \001(\002\022(\n repr"
  "esentative_crop_relative_key\030\010 \001(\t\022\030\n\020re"
  "presentative_x\030\t \001(\005\022\030\n\020representative_y"
  "\030\n \001(\005\022\034\n\024representative_width\030\013 \001(\005\022\035\n\025"
  "representative_height\030\014 \001(\005\022\035\n\025represent"
  "ative_pts_ns\030\r \001(\003\022\036\n\026representative_ord"
  "inal\030\016 \001(\005\022\026\n\016no_crop_reason\030\017 \001(\t\"R\n\023Tr"
  "ackTemplateFooter\022\016\n\006job_id\030\001 \001(\t\022\023\n\013seq"
  "uence_no\030\002 \001(\003\022\026\n\016template_count\030\003 \001(\003B4"
  "Z2github.com/mergenvision/backend/contra"
  "cts/video/v1b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_video_5ftrack_5ftemplate_5fv1_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_video_5ftrack_5ftemplate_5fv1_2eproto = {
    false, false, 860, descriptor_table_protodef_video_5ftrack_5ftemplate_5fv1_2eproto,
    "video_track_template_v1.proto",
    &descriptor_table_video_5ftrack_5ftemplate_5fv1_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_video_5ftrack_5ftemplate_5fv1_2eproto::offsets,
    file_level_metadata_video_5ftrack_5ftemplate_5fv1_2eproto, file_level_enum_descriptors_video_5ftrack_5ftemplate_5fv1_2eproto,
    file_level_service_descriptors_video_5ftrack_5ftemplate_5fv1_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_video_5ftrack_5ftemplate_5fv1_2eproto_getter() {
  return &descriptor_table_video_5ftrack_5ftemplate_5fv1_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_video_5ftrack_5ftemplate_5fv1_2eproto(&descriptor_table_video_5ftrack_5ftemplate_5fv1_2eproto);
namespace mergenvision {
namespace video {
namespace v1 {

// ===================================================================

class TrackTemplateBundle::_Internal {
 public:
};

TrackTemplateBundle::TrackTemplateBundle(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mergenvision.video.v1.TrackTemplateBundle)
}
TrackTemplateBundle::TrackTemplateBundle(const TrackTemplateBundle& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TrackTemplateBundle* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.templates_){from._impl_.templates_}
    , decltype(_impl_.job_id_){}
    , decltype(_impl_.video_id_){}
    , decltype(_impl_.model_version_){}
    , decltype(_impl_.preprocess_version_){}
    , decltype(_impl_.config_version_){}
    , decltype(_impl_.sequence_no_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_job_id().empty()) {
    _this->_impl_.job_id_.Set(from._internal_job_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.video_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.video_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_video_id().empty()) {
    _this->_impl_.video_id_.Set(from._internal_video_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.model_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.model_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_model_version().empty()) {
    _this->_impl_.model_version_.Set(from._internal_model_version(), 
      _this->GetArenaForAllocation());
  }
  _impl_.preprocess_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.preprocess_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_preprocess_version().empty()) {
    _this->_impl_.preprocess_version_.Set(from._internal_preprocess_version(), 
      _this->GetArenaForAllocation());
  }
  _impl_.config_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.config_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_config_version().empty()) {
    _this->_impl_.config_version_.Set(from._internal_config_version(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.sequence_no_ = from._impl_.sequence_no_;
  // @@protoc_insertion_point(copy_constructor:mergenvision.video.v1.TrackTemplateBundle)
}

inline void TrackTemplateBundle::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.templates_){arena}
    , decltype(_impl_.job_id_){}
    , decltype(_impl_.video_id_){}
    , decltype(_impl_.model_version_){}
    , decltype(_impl_.preprocess_version_){}
    , decltype(_impl_.config_version_){}
    , decltype(_impl_.sequence_no_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.video_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.video_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.model_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.model_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.preprocess_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.preprocess_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.config_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.config_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TrackTemplateBundle::~TrackTemplateBundle() {
  // @@protoc_insertion_point(destructor:mergenvision.video.v1.TrackTemplateBundle)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TrackTemplateBundle::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.templates_.~RepeatedPtrField();
  _impl_.job_id_.Destroy();
  _impl_.video_id_.Destroy();
  _impl_.model_version_.Destroy();
  _impl_.preprocess_version_.Destroy();
  _impl_.config_version_.Destroy();
}

void TrackTemplateBundle::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TrackTemplateBundle::Clear() {
// @@protoc_insertion_point(message_clear_start:mergenvision.video.v1.TrackTemplateBundle)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.templates_.Clear();
  _impl_.job_id_.ClearToEmpty();
  _impl_.video_id_.ClearToEmpty();
  _impl_.model_version_.ClearToEmpty();
  _impl_.preprocess_version_.ClearToEmpty();
  _impl_.config_version_.ClearToEmpty();
  _impl_.sequence_no_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TrackTemplateBundle::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string job_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_job_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.TrackTemplateBundle.job_id"));
        } else
          goto handle_unusual;
        continue;
      // string video_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_video_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.TrackTemplateBundle.video_id"));
        } else
          goto handle_unusual;
        continue;
      // int64 sequence_no = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.sequence_no_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string model_version = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_model_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.TrackTemplateBundle.model_version"));
        } else
          goto handle_unusual;
        continue;
      // string preprocess_version = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_preprocess_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.TrackTemplateBundle.preprocess_version"));
        } else
          goto handle_unusual;
        continue;
      // string config_version = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_config_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.TrackTemplateBundle.config_version"));
        } else
          goto handle_unusual;
        continue;
      // repeated .mergenvision.video.v1.RawTrackTemplate templates = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_templates(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TrackTemplateBundle::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mergenvision.video.v1.TrackTemplateBundle)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_job_id().data(), static_cast<int>(this->_internal_job_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.TrackTemplateBundle.job_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_job_id(), target);
  }

  // string video_id = 2;
  if (!this->_internal_video_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_video_id().data(), static_cast<int>(this->_internal_video_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.TrackTemplateBundle.video_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_video_id(), target);
  }

  // int64 sequence_no = 3;
  if (this->_internal_sequence_no() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_sequence_no(), target);
  }

  // string model_version = 4;
  if (!this->_internal_model_version().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_model_version().data(), static_cast<int>(this->_internal_model_version().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.TrackTemplateBundle.model_version");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_model_version(), target);
  }

  // string preprocess_version = 5;
  if (!this->_internal_preprocess_version().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_preprocess_version().data(), static_cast<int>(this->_internal_preprocess_version().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.TrackTemplateBundle.preprocess_version");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_preprocess_version(), target);
  }

  // string config_version = 6;
  if (!this->_internal_config_version().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_config_version().data(), static_cast<int>(this->_internal_config_version().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.TrackTemplateBundle.config_version");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_config_version(), target);
  }

  // repeated .mergenvision.video.v1.RawTrackTemplate templates = 7;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_templates_size()); i < n; i++) {
    const auto& repfield = this->_internal_templates(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(7, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mergenvision.video.v1.TrackTemplateBundle)
  return target;
}

size_t TrackTemplateBundle::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mergenvision.video.v1.TrackTemplateBundle)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .mergenvision.video.v1.RawTrackTemplate templates = 7;
  total_size += 1UL * this->_internal_templates_size();
  for (const auto& msg : this->_impl_.templates_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_job_id());
  }

  // string video_id = 2;
  if (!this->_internal_video_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_video_id());
  }

  // string model_version = 4;
  if (!this->_internal_model_version().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_model_version());
  }

  // string preprocess_version = 5;
  if (!this->_internal_preprocess_version().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_preprocess_version());
  }

  // string config_version = 6;
  if (!this->_internal_config_version().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_config_version());
  }

  // int64 sequence_no = 3;
  if (this->_internal_sequence_no() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_sequence_no());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TrackTemplateBundle::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TrackTemplateBundle::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TrackTemplateBundle::GetClassData() const { return &_class_data_; }


void TrackTemplateBundle::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TrackTemplateBundle*>(&to_msg);
  auto& from = static_cast<const TrackTemplateBundle&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mergenvision.video.v1.TrackTemplateBundle)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.templates_.MergeFrom(from._impl_.templates_);
  if (!from._internal_job_id().empty()) {
    _this->_internal_set_job_id(from._internal_job_id());
  }
  if (!from._internal_video_id().empty()) {
    _this->_internal_set_video_id(from._internal_video_id());
  }
  if (!from._internal_model_version().empty()) {
    _this->_internal_set_model_version(from._internal_model_version());
  }
  if (!from._internal_preprocess_version().empty()) {
    _this->_internal_set_preprocess_version(from._internal_preprocess_version());
  }
  if (!from._internal_config_version().empty()) {
    _this->_internal_set_config_version(from._internal_config_version());
  }
  if (from._internal_sequence_no() != 0) {
    _this->_internal_set_sequence_no(from._internal_sequence_no());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TrackTemplateBundle::CopyFrom(const TrackTemplateBundle& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mergenvision.video.v1.TrackTemplateBundle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TrackTemplateBundle::IsInitialized() const {
  return true;
}

void TrackTemplateBundle::InternalSwap(TrackTemplateBundle* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.templates_.InternalSwap(&other->_impl_.templates_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.job_id_, lhs_arena,
      &other->_impl_.job_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.video_id_, lhs_arena,
      &other->_impl_.video_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.model_version_, lhs_arena,
      &other->_impl_.model_version_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.preprocess_version_, lhs_arena,
      &other->_impl_.preprocess_version_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.config_version_, lhs_arena,
      &other->_impl_.config_version_, rhs_arena
  );
  swap(_impl_.sequence_no_, other->_impl_.sequence_no_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TrackTemplateBundle::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_video_5ftrack_5ftemplate_5fv1_2eproto_getter, &descriptor_table_video_5ftrack_5ftemplate_5fv1_2eproto_once,
      file_level_metadata_video_5ftrack_5ftemplate_5fv1_2eproto[0]);
}

// ===================================================================

class RawTrackTemplate::_Internal {
 public:
};

RawTrackTemplate::RawTrackTemplate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mergenvision.video.v1.RawTrackTemplate)
}
RawTrackTemplate::RawTrackTemplate(const RawTrackTemplate& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RawTrackTemplate* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.template_embedding_){from._impl_.template_embedding_}
    , decltype(_impl_.raw_track_key_){}
    , decltype(_impl_.representative_crop_relative_key_){}
    , decltype(_impl_.no_crop_reason_){}
    , decltype(_impl_.first_pts_ns_){}
    , decltype(_impl_.last_pts_ns_){}
    , decltype(_impl_.observation_count_){}
    , decltype(_impl_.eligible_observation_count_){}
    , decltype(_impl_.template_quality_){}
    , decltype(_impl_.representative_x_){}
    , decltype(_impl_.representative_y_){}
    , decltype(_impl_.representative_width_){}
    , decltype(_impl_.representative_pts_ns_){}
    , decltype(_impl_.representative_height_){}
    , decltype(_impl_.representative_ordinal_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.raw_track_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.raw_track_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_raw_track_key().empty()) {
    _this->_impl_.raw_track_key_.Set(from._internal_raw_track_key(), 
      _this->GetArenaForAllocation());
  }
  _impl_.representative_crop_relative_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.representative_crop_relative_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_representative_crop_relative_key().empty()) {
    _this->_impl_.representative_crop_relative_key_.Set(from._internal_representative_crop_relative_key(), 
      _this->GetArenaForAllocation());
  }
  _impl_.no_crop_reason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.no_crop_reason_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_no_crop_reason().empty()) {
    _this->_impl_.no_crop_reason_.Set(from._internal_no_crop_reason(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.first_pts_ns_, &from._impl_.first_pts_ns_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.representative_ordinal_) -
    reinterpret_cast<char*>(&_impl_.first_pts_ns_)) + sizeof(_impl_.representative_ordinal_));
  // @@protoc_insertion_point(copy_constructor:mergenvision.video.v1.RawTrackTemplate)
}

inline void RawTrackTemplate::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.template_embedding_){arena}
    , decltype(_impl_.raw_track_key_){}
    , decltype(_impl_.representative_crop_relative_key_){}
    , decltype(_impl_.no_crop_reason_){}
    , decltype(_impl_.first_pts_ns_){int64_t{0}}
    , decltype(_impl_.last_pts_ns_){int64_t{0}}
    , decltype(_impl_.observation_count_){int64_t{0}}
    , decltype(_impl_.eligible_observation_count_){int64_t{0}}
    , decltype(_impl_.template_quality_){0}
    , decltype(_impl_.representative_x_){0}
    , decltype(_impl_.representative_y_){0}
    , decltype(_impl_.representative_width_){0}
    , decltype(_impl_.representative_pts_ns_){int64_t{0}}
    , decltype(_impl_.representative_height_){0}
    , decltype(_impl_.representative_ordinal_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.raw_track_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.raw_track_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.representative_crop_relative_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.representative_crop_relative_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.no_crop_reason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.no_crop_reason_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RawTrackTemplate::~RawTrackTemplate() {
  // @@protoc_insertion_point(destructor:mergenvision.video.v1.RawTrackTemplate)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RawTrackTemplate::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.template_embedding_.~RepeatedField();
  _impl_.raw_track_key_.Destroy();
  _impl_.representative_crop_relative_key_.Destroy();
  _impl_.no_crop_reason_.Destroy();
}

void RawTrackTemplate::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RawTrackTemplate::Clear() {
// @@protoc_insertion_point(message_clear_start:mergenvision.video.v1.RawTrackTemplate)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.template_embedding_.Clear();
  _impl_.raw_track_key_.ClearToEmpty();
  _impl_.representative_crop_relative_key_.ClearToEmpty();
  _impl_.no_crop_reason_.ClearToEmpty();
  ::memset(&_impl_.first_pts_ns_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.representative_ordinal_) -
      reinterpret_cast<char*>(&_impl_.first_pts_ns_)) + sizeof(_impl_.representative_ordinal_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RawTrackTemplate::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string raw_track_key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_raw_track_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.RawTrackTemplate.raw_track_key"));
        } else
          goto handle_unusual;
        continue;
      // int64 first_pts_ns = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.first_pts_ns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 last_pts_ns = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.last_pts_ns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 observation_count = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.observation_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 eligible_observation_count = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.eligible_observation_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated float template_embedding = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_template_embedding(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 53) {
          _internal_add_template_embedding(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float template_quality = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 61)) {
          _impl_.template_quality_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // string representative_crop_relative_key = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_representative_crop_relative_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.RawTrackTemplate.representative_crop_relative_key"));
        } else
          goto handle_unusual;
        continue;
      // int32 representative_x = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.representative_x_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 representative_y = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.representative_y_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 representative_width = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 88)) {
          _impl_.representative_width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 representative_height = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          _impl_.representative_height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 representative_pts_ns = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 104)) {
          _impl_.representative_pts_ns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 representative_ordinal = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 112)) {
          _impl_.representative_ordinal_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string no_crop_reason = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 122)) {
          auto str = _internal_mutable_no_crop_reason();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.RawTrackTemplate.no_crop_reason"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RawTrackTemplate::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mergenvision.video.v1.RawTrackTemplate)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string raw_track_key = 1;
  if (!this->_internal_raw_track_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_raw_track_key().data(), static_cast<int>(this->_internal_raw_track_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.RawTrackTemplate.raw_track_key");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_raw_track_key(), target);
  }

  // int64 first_pts_ns = 2;
  if (this->_internal_first_pts_ns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_first_pts_ns(), target);
  }

  // int64 last_pts_ns = 3;
  if (this->_internal_last_pts_ns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_last_pts_ns(), target);
  }

  // int64 observation_count = 4;
  if (this->_internal_observation_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_observation_count(), target);
  }

  // int64 eligible_observation_count = 5;
  if (this->_internal_eligible_observation_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(5, this->_internal_eligible_observation_count(), target);
  }

  // repeated float template_embedding = 6;
  if (this->_internal_template_embedding_size() > 0) {
    target = stream->WriteFixedPacked(6, _internal_template_embedding(), target);
  }

  // float template_quality = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_template_quality = this->_internal_template_quality();
  uint32_t raw_template_quality;
  memcpy(&raw_template_quality, &tmp_template_quality, sizeof(tmp_template_quality));
  if (raw_template_quality != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(7, this->_internal_template_quality(), target);
  }

  // string representative_crop_relative_key = 8;
  if (!this->_internal_representative_crop_relative_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_representative_crop_relative_key().data(), static_cast<int>(this->_internal_representative_crop_relative_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.RawTrackTemplate.representative_crop_relative_key");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_representative_crop_relative_key(), target);
  }

  // int32 representative_x = 9;
  if (this->_internal_representative_x() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(9, this->_internal_representative_x(), target);
  }

  // int32 representative_y = 10;
  if (this->_internal_representative_y() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(10, this->_internal_representative_y(), target);
  }

  // int32 representative_width = 11;
  if (this->_internal_representative_width() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(11, this->_internal_representative_width(), target);
  }

  // int32 representative_height = 12;
  if (this->_internal_representative_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(12, this->_internal_representative_height(), target);
  }

  // int64 representative_pts_ns = 13;
  if (this->_internal_representative_pts_ns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(13, this->_internal_representative_pts_ns(), target);
  }

  // int32 representative_ordinal = 14;
  if (this->_internal_representative_ordinal() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(14, this->_internal_representative_ordinal(), target);
  }

  // string no_crop_reason = 15;
  if (!this->_internal_no_crop_reason().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_no_crop_reason().data(), static_cast<int>(this->_internal_no_crop_reason().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.RawTrackTemplate.no_crop_reason");
    target = stream->WriteStringMaybeAliased(
        15, this->_internal_no_crop_reason(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mergenvision.video.v1.RawTrackTemplate)
  return target;
}

size_t RawTrackTemplate::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mergenvision.video.v1.RawTrackTemplate)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float template_embedding = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_template_embedding_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // string raw_track_key = 1;
  if (!this->_internal_raw_track_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_raw_track_key());
  }

  // string representative_crop_relative_key = 8;
  if (!this->_internal_representative_crop_relative_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_representative_crop_relative_key());
  }

  // string no_crop_reason = 15;
  if (!this->_internal_no_crop_reason().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_no_crop_reason());
  }

  // int64 first_pts_ns = 2;
  if (this->_internal_first_pts_ns() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_first_pts_ns());
  }

  // int64 last_pts_ns = 3;
  if (this->_internal_last_pts_ns() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_last_pts_ns());
  }

  // int64 observation_count = 4;
  if (this->_internal_observation_count() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_observation_count());
  }

  // int64 eligible_observation_count = 5;
  if (this->_internal_eligible_observation_count() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_eligible_observation_count());
  }

  // float template_quality = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_template_quality = this->_internal_template_quality();
  uint32_t raw_template_quality;
  memcpy(&raw_template_quality, &tmp_template_quality, sizeof(tmp_template_quality));
  if (raw_template_quality != 0) {
    total_size += 1 + 4;
  }

  // int32 representative_x = 9;
  if (this->_internal_representative_x() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_representative_x());
  }

  // int32 representative_y = 10;
  if (this->_internal_representative_y() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_representative_y());
  }

  // int32 representative_width = 11;
  if (this->_internal_representative_width() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_representative_width());
  }

  // int64 representative_pts_ns = 13;
  if (this->_internal_representative_pts_ns() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_representative_pts_ns());
  }

  // int32 representative_height = 12;
  if (this->_internal_representative_height() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_representative_height());
  }

  // int32 representative_ordinal = 14;
  if (this->_internal_representative_ordinal() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_representative_ordinal());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RawTrackTemplate::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RawTrackTemplate::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RawTrackTemplate::GetClassData() const { return &_class_data_; }


void RawTrackTemplate::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RawTrackTemplate*>(&to_msg);
  auto& from = static_cast<const RawTrackTemplate&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mergenvision.video.v1.RawTrackTemplate)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.template_embedding_.MergeFrom(from._impl_.template_embedding_);
  if (!from._internal_raw_track_key().empty()) {
    _this->_internal_set_raw_track_key(from._internal_raw_track_key());
  }
  if (!from._internal_representative_crop_relative_key().empty()) {
    _this->_internal_set_representative_crop_relative_key(from._internal_representative_crop_relative_key());
  }
  if (!from._internal_no_crop_reason().empty()) {
    _this->_internal_set_no_crop_reason(from._internal_no_crop_reason());
  }
  if (from._internal_first_pts_ns() != 0) {
    _this->_internal_set_first_pts_ns(from._internal_first_pts_ns());
  }
  if (from._internal_last_pts_ns() != 0) {
    _this->_internal_set_last_pts_ns(from._internal_last_pts_ns());
  }
  if (from._internal_observation_count() != 0) {
    _this->_internal_set_observation_count(from._internal_observation_count());
  }
  if (from._internal_eligible_observation_count() != 0) {
    _this->_internal_set_eligible_observation_count(from._internal_eligible_observation_count());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_template_quality = from._internal_template_quality();
  uint32_t raw_template_quality;
  memcpy(&raw_template_quality, &tmp_template_quality, sizeof(tmp_template_quality));
  if (raw_template_quality != 0) {
    _this->_internal_set_template_quality(from._internal_template_quality());
  }
  if (from._internal_representative_x() != 0) {
    _this->_internal_set_representative_x(from._internal_representative_x());
  }
  if (from._internal_representative_y() != 0) {
    _this->_internal_set_representative_y(from._internal_representative_y());
  }
  if (from._internal_representative_width() != 0) {
    _this->_internal_set_representative_width(from._internal_representative_width());
  }
  if (from._internal_representative_pts_ns() != 0) {
    _this->_internal_set_representative_pts_ns(from._internal_representative_pts_ns());
  }
  if (from._internal_representative_height() != 0) {
    _this->_internal_set_representative_height(from._internal_representative_height());
  }
  if (from._internal_representative_ordinal() != 0) {
    _this->_internal_set_representative_ordinal(from._internal_representative_ordinal());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RawTrackTemplate::CopyFrom(const RawTrackTemplate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mergenvision.video.v1.RawTrackTemplate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RawTrackTemplate::IsInitialized() const {
  return true;
}

void RawTrackTemplate::InternalSwap(RawTrackTemplate* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.template_embedding_.InternalSwap(&other->_impl_.template_embedding_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.raw_track_key_, lhs_arena,
      &other->_impl_.raw_track_key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.representative_crop_relative_key_, lhs_arena,
      &other->_impl_.representative_crop_relative_key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.no_crop_reason_, lhs_arena,
      &other->_impl_.no_crop_reason_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RawTrackTemplate, _impl_.representative_ordinal_)
      + sizeof(RawTrackTemplate::_impl_.representative_ordinal_)
      - PROTOBUF_FIELD_OFFSET(RawTrackTemplate, _impl_.first_pts_ns_)>(
          reinterpret_cast<char*>(&_impl_.first_pts_ns_),
          reinterpret_cast<char*>(&other->_impl_.first_pts_ns_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RawTrackTemplate::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_video_5ftrack_5ftemplate_5fv1_2eproto_getter, &descriptor_table_video_5ftrack_5ftemplate_5fv1_2eproto_once,
      file_level_metadata_video_5ftrack_5ftemplate_5fv1_2eproto[1]);
}

// ===================================================================

class TrackTemplateFooter::_Internal {
 public:
};

TrackTemplateFooter::TrackTemplateFooter(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mergenvision.video.v1.TrackTemplateFooter)
}
TrackTemplateFooter::TrackTemplateFooter(const TrackTemplateFooter& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TrackTemplateFooter* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.job_id_){}
    , decltype(_impl_.sequence_no_){}
    , decltype(_impl_.template_count_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_job_id().empty()) {
    _this->_impl_.job_id_.Set(from._internal_job_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.sequence_no_, &from._impl_.sequence_no_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.template_count_) -
    reinterpret_cast<char*>(&_impl_.sequence_no_)) + sizeof(_impl_.template_count_));
  // @@protoc_insertion_point(copy_constructor:mergenvision.video.v1.TrackTemplateFooter)
}

inline void TrackTemplateFooter::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.job_id_){}
    , decltype(_impl_.sequence_no_){int64_t{0}}
    , decltype(_impl_.template_count_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TrackTemplateFooter::~TrackTemplateFooter() {
  // @@protoc_insertion_point(destructor:mergenvision.video.v1.TrackTemplateFooter)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TrackTemplateFooter::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.job_id_.Destroy();
}

void TrackTemplateFooter::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TrackTemplateFooter::Clear() {
// @@protoc_insertion_point(message_clear_start:mergenvision.video.v1.TrackTemplateFooter)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.job_id_.ClearToEmpty();
  ::memset(&_impl_.sequence_no_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.template_count_) -
      reinterpret_cast<char*>(&_impl_.sequence_no_)) + sizeof(_impl_.template_count_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TrackTemplateFooter::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string job_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_job_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.TrackTemplateFooter.job_id"));
        } else
          goto handle_unusual;
        continue;
      // int64 sequence_no = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.sequence_no_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 template_count = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.template_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TrackTemplateFooter::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mergenvision.video.v1.TrackTemplateFooter)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_job_id().data(), static_cast<int>(this->_internal_job_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.TrackTemplateFooter.job_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_job_id(), target);
  }

  // int64 sequence_no = 2;
  if (this->_internal_sequence_no() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_sequence_no(), target);
  }

  // int64 template_count = 3;
  if (this->_internal_template_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_template_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mergenvision.video.v1.TrackTemplateFooter)
  return target;
}

size_t TrackTemplateFooter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mergenvision.video.v1.TrackTemplateFooter)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_job_id());
  }

  // int64 sequence_no = 2;
  if (this->_internal_sequence_no() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_sequence_no());
  }

  // int64 template_count = 3;
  if (this->_internal_template_count() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_template_count());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TrackTemplateFooter::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TrackTemplateFooter::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TrackTemplateFooter::GetClassData() const { return &_class_data_; }


void TrackTemplateFooter::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TrackTemplateFooter*>(&to_msg);
  auto& from = static_cast<const TrackTemplateFooter&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mergenvision.video.v1.TrackTemplateFooter)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_job_id().empty()) {
    _this->_internal_set_job_id(from._internal_job_id());
  }
  if (from._internal_sequence_no() != 0) {
    _this->_internal_set_sequence_no(from._internal_sequence_no());
  }
  if (from._internal_template_count() != 0) {
    _this->_internal_set_template_count(from._internal_template_count());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TrackTemplateFooter::CopyFrom(const TrackTemplateFooter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mergenvision.video.v1.TrackTemplateFooter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TrackTemplateFooter::IsInitialized() const {
  return true;
}

void TrackTemplateFooter::InternalSwap(TrackTemplateFooter* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.job_id_, lhs_arena,
      &other->_impl_.job_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TrackTemplateFooter, _impl_.template_count_)
      + sizeof(TrackTemplateFooter::_impl_.template_count_)
      - PROTOBUF_FIELD_OFFSET(TrackTemplateFooter, _impl_.sequence_no_)>(
          reinterpret_cast<char*>(&_impl_.sequence_no_),
          reinterpret_cast<char*>(&other->_impl_.sequence_no_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TrackTemplateFooter::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_video_5ftrack_5ftemplate_5fv1_2eproto_getter, &descriptor_table_video_5ftrack_5ftemplate_5fv1_2eproto_once,
      file_level_metadata_video_5ftrack_5ftemplate_5fv1_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace video
}  // namespace mergenvision
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mergenvision::video::v1::TrackTemplateBundle*
Arena::CreateMaybeMessage< ::mergenvision::video::v1::TrackTemplateBundle >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mergenvision::video::v1::TrackTemplateBundle >(arena);
}
template<> PROTOBUF_NOINLINE ::mergenvision::video::v1::RawTrackTemplate*
Arena::CreateMaybeMessage< ::mergenvision::video::v1::RawTrackTemplate >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mergenvision::video::v1::RawTrackTemplate >(arena);
}
template<> PROTOBUF_NOINLINE ::mergenvision::video::v1::TrackTemplateFooter*
Arena::CreateMaybeMessage< ::mergenvision::video::v1::TrackTemplateFooter >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mergenvision::video::v1::TrackTemplateFooter >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
