// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_track_template_v1.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_video_5ftrack_5ftemplate_5fv1_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_video_5ftrack_5ftemplate_5fv1_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_video_5ftrack_5ftemplate_5fv1_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_video_5ftrack_5ftemplate_5fv1_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_video_5ftrack_5ftemplate_5fv1_2eproto;
namespace mergenvision {
namespace video {
namespace v1 {
class RawTrackTemplate;
struct RawTrackTemplateDefaultTypeInternal;
extern RawTrackTemplateDefaultTypeInternal _RawTrackTemplate_default_instance_;
class TrackTemplateBundle;
struct TrackTemplateBundleDefaultTypeInternal;
extern TrackTemplateBundleDefaultTypeInternal _TrackTemplateBundle_default_instance_;
class TrackTemplateFooter;
struct TrackTemplateFooterDefaultTypeInternal;
extern TrackTemplateFooterDefaultTypeInternal _TrackTemplateFooter_default_instance_;
}  // namespace v1
}  // namespace video
}  // namespace mergenvision
PROTOBUF_NAMESPACE_OPEN
template<> ::mergenvision::video::v1::RawTrackTemplate* Arena::CreateMaybeMessage<::mergenvision::video::v1::RawTrackTemplate>(Arena*);
template<> ::mergenvision::video::v1::TrackTemplateBundle* Arena::CreateMaybeMessage<::mergenvision::video::v1::TrackTemplateBundle>(Arena*);
template<> ::mergenvision::video::v1::TrackTemplateFooter* Arena::CreateMaybeMessage<::mergenvision::video::v1::TrackTemplateFooter>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mergenvision {
namespace video {
namespace v1 {

// ===================================================================

class TrackTemplateBundle final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mergenvision.video.v1.TrackTemplateBundle) */ {
 public:
  inline TrackTemplateBundle() : TrackTemplateBundle(nullptr) {}
  ~TrackTemplateBundle() override;
  explicit PROTOBUF_CONSTEXPR TrackTemplateBundle(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TrackTemplateBundle(const TrackTemplateBundle& from);
  TrackTemplateBundle(TrackTemplateBundle&& from) noexcept
    : TrackTemplateBundle() {
    *this = ::std::move(from);
  }

  inline TrackTemplateBundle& operator=(const TrackTemplateBundle& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrackTemplateBundle& operator=(TrackTemplateBundle&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrackTemplateBundle& default_instance() {
    return *internal_default_instance();
  }
  static inline const TrackTemplateBundle* internal_default_instance() {
    return reinterpret_cast<const TrackTemplateBundle*>(
               &_TrackTemplateBundle_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TrackTemplateBundle& a, TrackTemplateBundle& b) {
    a.Swap(&b);
  }
  inline void Swap(TrackTemplateBundle* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrackTemplateBundle* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrackTemplateBundle* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TrackTemplateBundle>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TrackTemplateBundle& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TrackTemplateBundle& from) {
    TrackTemplateBundle::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrackTemplateBundle* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mergenvision.video.v1.TrackTemplateBundle";
  }
  protected:
  explicit TrackTemplateBundle(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTemplatesFieldNumber = 7,
    kJobIdFieldNumber = 1,
    kVideoIdFieldNumber = 2,
    kModelVersionFieldNumber = 4,
    kPreprocessVersionFieldNumber = 5,
    kConfigVersionFieldNumber = 6,
    kSequenceNoFieldNumber = 3,
  };
  // repeated .mergenvision.video.v1.RawTrackTemplate templates = 7;
  int templates_size() const;
  private:
  int _internal_templates_size() const;
  public:
  void clear_templates();
  ::mergenvision::video::v1::RawTrackTemplate* mutable_templates(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mergenvision::video::v1::RawTrackTemplate >*
      mutable_templates();
  private:
  const ::mergenvision::video::v1::RawTrackTemplate& _internal_templates(int index) const;
  ::mergenvision::video::v1::RawTrackTemplate* _internal_add_templates();
  public:
  const ::mergenvision::video::v1::RawTrackTemplate& templates(int index) const;
  ::mergenvision::video::v1::RawTrackTemplate* add_templates();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mergenvision::video::v1::RawTrackTemplate >&
      templates() const;

  // string job_id = 1;
  void clear_job_id();
  const std::string& job_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_job_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_job_id();
  PROTOBUF_NODISCARD std::string* release_job_id();
  void set_allocated_job_id(std::string* job_id);
  private:
  const std::string& _internal_job_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_job_id(const std::string& value);
  std::string* _internal_mutable_job_id();
  public:

  // string video_id = 2;
  void clear_video_id();
  const std::string& video_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_video_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_video_id();
  PROTOBUF_NODISCARD std::string* release_video_id();
  void set_allocated_video_id(std::string* video_id);
  private:
  const std::string& _internal_video_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_video_id(const std::string& value);
  std::string* _internal_mutable_video_id();
  public:

  // string model_version = 4;
  void clear_model_version();
  const std::string& model_version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_model_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_model_version();
  PROTOBUF_NODISCARD std::string* release_model_version();
  void set_allocated_model_version(std::string* model_version);
  private:
  const std::string& _internal_model_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_model_version(const std::string& value);
  std::string* _internal_mutable_model_version();
  public:

  // string preprocess_version = 5;
  void clear_preprocess_version();
  const std::string& preprocess_version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_preprocess_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_preprocess_version();
  PROTOBUF_NODISCARD std::string* release_preprocess_version();
  void set_allocated_preprocess_version(std::string* preprocess_version);
  private:
  const std::string& _internal_preprocess_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_preprocess_version(const std::string& value);
  std::string* _internal_mutable_preprocess_version();
  public:

  // string config_version = 6;
  void clear_config_version();
  const std::string& config_version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_config_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_config_version();
  PROTOBUF_NODISCARD std::string* release_config_version();
  void set_allocated_config_version(std::string* config_version);
  private:
  const std::string& _internal_config_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_config_version(const std::string& value);
  std::string* _internal_mutable_config_version();
  public:

  // int64 sequence_no = 3;
  void clear_sequence_no();
  int64_t sequence_no() const;
  void set_sequence_no(int64_t value);
  private:
  int64_t _internal_sequence_no() const;
  void _internal_set_sequence_no(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:mergenvision.video.v1.TrackTemplateBundle)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mergenvision::video::v1::RawTrackTemplate > templates_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr job_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr video_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr model_version_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr preprocess_version_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr config_version_;
    int64_t sequence_no_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5ftrack_5ftemplate_5fv1_2eproto;
};
// -------------------------------------------------------------------

class RawTrackTemplate final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mergenvision.video.v1.RawTrackTemplate) */ {
 public:
  inline RawTrackTemplate() : RawTrackTemplate(nullptr) {}
  ~RawTrackTemplate() override;
  explicit PROTOBUF_CONSTEXPR RawTrackTemplate(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RawTrackTemplate(const RawTrackTemplate& from);
  RawTrackTemplate(RawTrackTemplate&& from) noexcept
    : RawTrackTemplate() {
    *this = ::std::move(from);
  }

  inline RawTrackTemplate& operator=(const RawTrackTemplate& from) {
    CopyFrom(from);
    return *this;
  }
  inline RawTrackTemplate& operator=(RawTrackTemplate&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RawTrackTemplate& default_instance() {
    return *internal_default_instance();
  }
  static inline const RawTrackTemplate* internal_default_instance() {
    return reinterpret_cast<const RawTrackTemplate*>(
               &_RawTrackTemplate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RawTrackTemplate& a, RawTrackTemplate& b) {
    a.Swap(&b);
  }
  inline void Swap(RawTrackTemplate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RawTrackTemplate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RawTrackTemplate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RawTrackTemplate>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RawTrackTemplate& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RawTrackTemplate& from) {
    RawTrackTemplate::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RawTrackTemplate* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mergenvision.video.v1.RawTrackTemplate";
  }
  protected:
  explicit RawTrackTemplate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTemplateEmbeddingFieldNumber = 6,
    kRawTrackKeyFieldNumber = 1,
    kRepresentativeCropRelativeKeyFieldNumber = 8,
    kNoCropReasonFieldNumber = 15,
    kFirstPtsNsFieldNumber = 2,
    kLastPtsNsFieldNumber = 3,
    kObservationCountFieldNumber = 4,
    kEligibleObservationCountFieldNumber = 5,
    kTemplateQualityFieldNumber = 7,
    kRepresentativeXFieldNumber = 9,
    kRepresentativeYFieldNumber = 10,
    kRepresentativeWidthFieldNumber = 11,
    kRepresentativePtsNsFieldNumber = 13,
    kRepresentativeHeightFieldNumber = 12,
    kRepresentativeOrdinalFieldNumber = 14,
  };
  // repeated float template_embedding = 6;
  int template_embedding_size() const;
  private:
  int _internal_template_embedding_size() const;
  public:
  void clear_template_embedding();
  private:
  float _internal_template_embedding(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_template_embedding() const;
  void _internal_add_template_embedding(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_template_embedding();
  public:
  float template_embedding(int index) const;
  void set_template_embedding(int index, float value);
  void add_template_embedding(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      template_embedding() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_template_embedding();

  // string raw_track_key = 1;
  void clear_raw_track_key();
  const std::string& raw_track_key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_raw_track_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_raw_track_key();
  PROTOBUF_NODISCARD std::string* release_raw_track_key();
  void set_allocated_raw_track_key(std::string* raw_track_key);
  private:
  const std::string& _internal_raw_track_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_raw_track_key(const std::string& value);
  std::string* _internal_mutable_raw_track_key();
  public:

  // string representative_crop_relative_key = 8;
  void clear_representative_crop_relative_key();
  const std::string& representative_crop_relative_key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_representative_crop_relative_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_representative_crop_relative_key();
  PROTOBUF_NODISCARD std::string* release_representative_crop_relative_key();
  void set_allocated_representative_crop_relative_key(std::string* representative_crop_relative_key);
  private:
  const std::string& _internal_representative_crop_relative_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_representative_crop_relative_key(const std::string& value);
  std::string* _internal_mutable_representative_crop_relative_key();
  public:

  // string no_crop_reason = 15;
  void clear_no_crop_reason();
  const std::string& no_crop_reason() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_no_crop_reason(ArgT0&& arg0, ArgT... args);
  std::string* mutable_no_crop_reason();
  PROTOBUF_NODISCARD std::string* release_no_crop_reason();
  void set_allocated_no_crop_reason(std::string* no_crop_reason);
  private:
  const std::string& _internal_no_crop_reason() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_no_crop_reason(const std::string& value);
  std::string* _internal_mutable_no_crop_reason();
  public:

  // int64 first_pts_ns = 2;
  void clear_first_pts_ns();
  int64_t first_pts_ns() const;
  void set_first_pts_ns(int64_t value);
  private:
  int64_t _internal_first_pts_ns() const;
  void _internal_set_first_pts_ns(int64_t value);
  public:

  // int64 last_pts_ns = 3;
  void clear_last_pts_ns();
  int64_t last_pts_ns() const;
  void set_last_pts_ns(int64_t value);
  private:
  int64_t _internal_last_pts_ns() const;
  void _internal_set_last_pts_ns(int64_t value);
  public:

  // int64 observation_count = 4;
  void clear_observation_count();
  int64_t observation_count() const;
  void set_observation_count(int64_t value);
  private:
  int64_t _internal_observation_count() const;
  void _internal_set_observation_count(int64_t value);
  public:

  // int64 eligible_observation_count = 5;
  void clear_eligible_observation_count();
  int64_t eligible_observation_count() const;
  void set_eligible_observation_count(int64_t value);
  private:
  int64_t _internal_eligible_observation_count() const;
  void _internal_set_eligible_observation_count(int64_t value);
  public:

  // float template_quality = 7;
  void clear_template_quality();
  float template_quality() const;
  void set_template_quality(float value);
  private:
  float _internal_template_quality() const;
  void _internal_set_template_quality(float value);
  public:

  // int32 representative_x = 9;
  void clear_representative_x();
  int32_t representative_x() const;
  void set_representative_x(int32_t value);
  private:
  int32_t _internal_representative_x() const;
  void _internal_set_representative_x(int32_t value);
  public:

  // int32 representative_y = 10;
  void clear_representative_y();
  int32_t representative_y() const;
  void set_representative_y(int32_t value);
  private:
  int32_t _internal_representative_y() const;
  void _internal_set_representative_y(int32_t value);
  public:

  // int32 representative_width = 11;
  void clear_representative_width();
  int32_t representative_width() const;
  void set_representative_width(int32_t value);
  private:
  int32_t _internal_representative_width() const;
  void _internal_set_representative_width(int32_t value);
  public:

  // int64 representative_pts_ns = 13;
  void clear_representative_pts_ns();
  int64_t representative_pts_ns() const;
  void set_representative_pts_ns(int64_t value);
  private:
  int64_t _internal_representative_pts_ns() const;
  void _internal_set_representative_pts_ns(int64_t value);
  public:

  // int32 representative_height = 12;
  void clear_representative_height();
  int32_t representative_height() const;
  void set_representative_height(int32_t value);
  private:
  int32_t _internal_representative_height() const;
  void _internal_set_representative_height(int32_t value);
  public:

  // int32 representative_ordinal = 14;
  void clear_representative_ordinal();
  int32_t representative_ordinal() const;
  void set_representative_ordinal(int32_t value);
  private:
  int32_t _internal_representative_ordinal() const;
  void _internal_set_representative_ordinal(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:mergenvision.video.v1.RawTrackTemplate)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > template_embedding_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr raw_track_key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr representative_crop_relative_key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr no_crop_reason_;
    int64_t first_pts_ns_;
    int64_t last_pts_ns_;
    int64_t observation_count_;
    int64_t eligible_observation_count_;
    float template_quality_;
    int32_t representative_x_;
    int32_t representative_y_;
    int32_t representative_width_;
    int64_t representative_pts_ns_;
    int32_t representative_height_;
    int32_t representative_ordinal_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5ftrack_5ftemplate_5fv1_2eproto;
};
// -------------------------------------------------------------------

class TrackTemplateFooter final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mergenvision.video.v1.TrackTemplateFooter) */ {
 public:
  inline TrackTemplateFooter() : TrackTemplateFooter(nullptr) {}
  ~TrackTemplateFooter() override;
  explicit PROTOBUF_CONSTEXPR TrackTemplateFooter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TrackTemplateFooter(const TrackTemplateFooter& from);
  TrackTemplateFooter(TrackTemplateFooter&& from) noexcept
    : TrackTemplateFooter() {
    *this = ::std::move(from);
  }

  inline TrackTemplateFooter& operator=(const TrackTemplateFooter& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrackTemplateFooter& operator=(TrackTemplateFooter&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrackTemplateFooter& default_instance() {
    return *internal_default_instance();
  }
  static inline const TrackTemplateFooter* internal_default_instance() {
    return reinterpret_cast<const TrackTemplateFooter*>(
               &_TrackTemplateFooter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(TrackTemplateFooter& a, TrackTemplateFooter& b) {
    a.Swap(&b);
  }
  inline void Swap(TrackTemplateFooter* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrackTemplateFooter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrackTemplateFooter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TrackTemplateFooter>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TrackTemplateFooter& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TrackTemplateFooter& from) {
    TrackTemplateFooter::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrackTemplateFooter* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mergenvision.video.v1.TrackTemplateFooter";
  }
  protected:
  explicit TrackTemplateFooter(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJobIdFieldNumber = 1,
    kSequenceNoFieldNumber = 2,
    kTemplateCountFieldNumber = 3,
  };
  // string job_id = 1;
  void clear_job_id();
  const std::string& job_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_job_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_job_id();
  PROTOBUF_NODISCARD std::string* release_job_id();
  void set_allocated_job_id(std::string* job_id);
  private:
  const std::string& _internal_job_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_job_id(const std::string& value);
  std::string* _internal_mutable_job_id();
  public:

  // int64 sequence_no = 2;
  void clear_sequence_no();
  int64_t sequence_no() const;
  void set_sequence_no(int64_t value);
  private:
  int64_t _internal_sequence_no() const;
  void _internal_set_sequence_no(int64_t value);
  public:

  // int64 template_count = 3;
  void clear_template_count();
  int64_t template_count() const;
  void set_template_count(int64_t value);
  private:
  int64_t _internal_template_count() const;
  void _internal_set_template_count(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:mergenvision.video.v1.TrackTemplateFooter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr job_id_;
    int64_t sequence_no_;
    int64_t template_count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5ftrack_5ftemplate_5fv1_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TrackTemplateBundle

// string job_id = 1;
inline void TrackTemplateBundle::clear_job_id() {
  _impl_.job_id_.ClearToEmpty();
}
inline const std::string& TrackTemplateBundle::job_id() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.TrackTemplateBundle.job_id)
  return _internal_job_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TrackTemplateBundle::set_job_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.job_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.TrackTemplateBundle.job_id)
}
inline std::string* TrackTemplateBundle::mutable_job_id() {
  std::string* _s = _internal_mutable_job_id();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.TrackTemplateBundle.job_id)
  return _s;
}
inline const std::string& TrackTemplateBundle::_internal_job_id() const {
  return _impl_.job_id_.Get();
}
inline void TrackTemplateBundle::_internal_set_job_id(const std::string& value) {
  
  _impl_.job_id_.Set(value, GetArenaForAllocation());
}
inline std::string* TrackTemplateBundle::_internal_mutable_job_id() {
  
  return _impl_.job_id_.Mutable(GetArenaForAllocation());
}
inline std::string* TrackTemplateBundle::release_job_id() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.TrackTemplateBundle.job_id)
  return _impl_.job_id_.Release();
}
inline void TrackTemplateBundle::set_allocated_job_id(std::string* job_id) {
  if (job_id != nullptr) {
    
  } else {
    
  }
  _impl_.job_id_.SetAllocated(job_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.job_id_.IsDefault()) {
    _impl_.job_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.TrackTemplateBundle.job_id)
}

// string video_id = 2;
inline void TrackTemplateBundle::clear_video_id() {
  _impl_.video_id_.ClearToEmpty();
}
inline const std::string& TrackTemplateBundle::video_id() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.TrackTemplateBundle.video_id)
  return _internal_video_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TrackTemplateBundle::set_video_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.video_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.TrackTemplateBundle.video_id)
}
inline std::string* TrackTemplateBundle::mutable_video_id() {
  std::string* _s = _internal_mutable_video_id();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.TrackTemplateBundle.video_id)
  return _s;
}
inline const std::string& TrackTemplateBundle::_internal_video_id() const {
  return _impl_.video_id_.Get();
}
inline void TrackTemplateBundle::_internal_set_video_id(const std::string& value) {
  
  _impl_.video_id_.Set(value, GetArenaForAllocation());
}
inline std::string* TrackTemplateBundle::_internal_mutable_video_id() {
  
  return _impl_.video_id_.Mutable(GetArenaForAllocation());
}
inline std::string* TrackTemplateBundle::release_video_id() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.TrackTemplateBundle.video_id)
  return _impl_.video_id_.Release();
}
inline void TrackTemplateBundle::set_allocated_video_id(std::string* video_id) {
  if (video_id != nullptr) {
    
  } else {
    
  }
  _impl_.video_id_.SetAllocated(video_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.video_id_.IsDefault()) {
    _impl_.video_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.TrackTemplateBundle.video_id)
}

// int64 sequence_no = 3;
inline void TrackTemplateBundle::clear_sequence_no() {
  _impl_.sequence_no_ = int64_t{0};
}
inline int64_t TrackTemplateBundle::_internal_sequence_no() const {
  return _impl_.sequence_no_;
}
inline int64_t TrackTemplateBundle::sequence_no() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.TrackTemplateBundle.sequence_no)
  return _internal_sequence_no();
}
inline void TrackTemplateBundle::_internal_set_sequence_no(int64_t value) {
  
  _impl_.sequence_no_ = value;
}
inline void TrackTemplateBundle::set_sequence_no(int64_t value) {
  _internal_set_sequence_no(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.TrackTemplateBundle.sequence_no)
}

// string model_version = 4;
inline void TrackTemplateBundle::clear_model_version() {
  _impl_.model_version_.ClearToEmpty();
}
inline const std::string& TrackTemplateBundle::model_version() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.TrackTemplateBundle.model_version)
  return _internal_model_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TrackTemplateBundle::set_model_version(ArgT0&& arg0, ArgT... args) {
 
 _impl_.model_version_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.TrackTemplateBundle.model_version)
}
inline std::string* TrackTemplateBundle::mutable_model_version() {
  std::string* _s = _internal_mutable_model_version();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.TrackTemplateBundle.model_version)
  return _s;
}
inline const std::string& TrackTemplateBundle::_internal_model_version() const {
  return _impl_.model_version_.Get();
}
inline void TrackTemplateBundle::_internal_set_model_version(const std::string& value) {
  
  _impl_.model_version_.Set(value, GetArenaForAllocation());
}
inline std::string* TrackTemplateBundle::_internal_mutable_model_version() {
  
  return _impl_.model_version_.Mutable(GetArenaForAllocation());
}
inline std::string* TrackTemplateBundle::release_model_version() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.TrackTemplateBundle.model_version)
  return _impl_.model_version_.Release();
}
inline void TrackTemplateBundle::set_allocated_model_version(std::string* model_version) {
  if (model_version != nullptr) {
    
  } else {
    
  }
  _impl_.model_version_.SetAllocated(model_version, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.model_version_.IsDefault()) {
    _impl_.model_version_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.TrackTemplateBundle.model_version)
}

// string preprocess_version = 5;
inline void TrackTemplateBundle::clear_preprocess_version() {
  _impl_.preprocess_version_.ClearToEmpty();
}
inline const std::string& TrackTemplateBundle::preprocess_version() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.TrackTemplateBundle.preprocess_version)
  return _internal_preprocess_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TrackTemplateBundle::set_preprocess_version(ArgT0&& arg0, ArgT... args) {
 
 _impl_.preprocess_version_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.TrackTemplateBundle.preprocess_version)
}
inline std::string* TrackTemplateBundle::mutable_preprocess_version() {
  std::string* _s = _internal_mutable_preprocess_version();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.TrackTemplateBundle.preprocess_version)
  return _s;
}
inline const std::string& TrackTemplateBundle::_internal_preprocess_version() const {
  return _impl_.preprocess_version_.Get();
}
inline void TrackTemplateBundle::_internal_set_preprocess_version(const std::string& value) {
  
  _impl_.preprocess_version_.Set(value, GetArenaForAllocation());
}
inline std::string* TrackTemplateBundle::_internal_mutable_preprocess_version() {
  
  return _impl_.preprocess_version_.Mutable(GetArenaForAllocation());
}
inline std::string* TrackTemplateBundle::release_preprocess_version() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.TrackTemplateBundle.preprocess_version)
  return _impl_.preprocess_version_.Release();
}
inline void TrackTemplateBundle::set_allocated_preprocess_version(std::string* preprocess_version) {
  if (preprocess_version != nullptr) {
    
  } else {
    
  }
  _impl_.preprocess_version_.SetAllocated(preprocess_version, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.preprocess_version_.IsDefault()) {
    _impl_.preprocess_version_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.TrackTemplateBundle.preprocess_version)
}

// string config_version = 6;
inline void TrackTemplateBundle::clear_config_version() {
  _impl_.config_version_.ClearToEmpty();
}
inline const std::string& TrackTemplateBundle::config_version() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.TrackTemplateBundle.config_version)
  return _internal_config_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TrackTemplateBundle::set_config_version(ArgT0&& arg0, ArgT... args) {
 
 _impl_.config_version_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.TrackTemplateBundle.config_version)
}
inline std::string* TrackTemplateBundle::mutable_config_version() {
  std::string* _s = _internal_mutable_config_version();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.TrackTemplateBundle.config_version)
  return _s;
}
inline const std::string& TrackTemplateBundle::_internal_config_version() const {
  return _impl_.config_version_.Get();
}
inline void TrackTemplateBundle::_internal_set_config_version(const std::string& value) {
  
  _impl_.config_version_.Set(value, GetArenaForAllocation());
}
inline std::string* TrackTemplateBundle::_internal_mutable_config_version() {
  
  return _impl_.config_version_.Mutable(GetArenaForAllocation());
}
inline std::string* TrackTemplateBundle::release_config_version() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.TrackTemplateBundle.config_version)
  return _impl_.config_version_.Release();
}
inline void TrackTemplateBundle::set_allocated_config_version(std::string* config_version) {
  if (config_version != nullptr) {
    
  } else {
    
  }
  _impl_.config_version_.SetAllocated(config_version, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.config_version_.IsDefault()) {
    _impl_.config_version_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.TrackTemplateBundle.config_version)
}

// repeated .mergenvision.video.v1.RawTrackTemplate templates = 7;
inline int TrackTemplateBundle::_internal_templates_size() const {
  return _impl_.templates_.size();
}
inline int TrackTemplateBundle::templates_size() const {
  return _internal_templates_size();
}
inline void TrackTemplateBundle::clear_templates() {
  _impl_.templates_.Clear();
}
inline ::mergenvision::video::v1::RawTrackTemplate* TrackTemplateBundle::mutable_templates(int index) {
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.TrackTemplateBundle.templates)
  return _impl_.templates_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mergenvision::video::v1::RawTrackTemplate >*
TrackTemplateBundle::mutable_templates() {
  // @@protoc_insertion_point(field_mutable_list:mergenvision.video.v1.TrackTemplateBundle.templates)
  return &_impl_.templates_;
}
inline const ::mergenvision::video::v1::RawTrackTemplate& TrackTemplateBundle::_internal_templates(int index) const {
  return _impl_.templates_.Get(index);
}
inline const ::mergenvision::video::v1::RawTrackTemplate& TrackTemplateBundle::templates(int index) const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.TrackTemplateBundle.templates)
  return _internal_templates(index);
}
inline ::mergenvision::video::v1::RawTrackTemplate* TrackTemplateBundle::_internal_add_templates() {
  return _impl_.templates_.Add();
}
inline ::mergenvision::video::v1::RawTrackTemplate* TrackTemplateBundle::add_templates() {
  ::mergenvision::video::v1::RawTrackTemplate* _add = _internal_add_templates();
  // @@protoc_insertion_point(field_add:mergenvision.video.v1.TrackTemplateBundle.templates)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mergenvision::video::v1::RawTrackTemplate >&
TrackTemplateBundle::templates() const {
  // @@protoc_insertion_point(field_list:mergenvision.video.v1.TrackTemplateBundle.templates)
  return _impl_.templates_;
}

// -------------------------------------------------------------------

// RawTrackTemplate

// string raw_track_key = 1;
inline void RawTrackTemplate::clear_raw_track_key() {
  _impl_.raw_track_key_.ClearToEmpty();
}
inline const std::string& RawTrackTemplate::raw_track_key() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.RawTrackTemplate.raw_track_key)
  return _internal_raw_track_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RawTrackTemplate::set_raw_track_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.raw_track_key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.RawTrackTemplate.raw_track_key)
}
inline std::string* RawTrackTemplate::mutable_raw_track_key() {
  std::string* _s = _internal_mutable_raw_track_key();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.RawTrackTemplate.raw_track_key)
  return _s;
}
inline const std::string& RawTrackTemplate::_internal_raw_track_key() const {
  return _impl_.raw_track_key_.Get();
}
inline void RawTrackTemplate::_internal_set_raw_track_key(const std::string& value) {
  
  _impl_.raw_track_key_.Set(value, GetArenaForAllocation());
}
inline std::string* RawTrackTemplate::_internal_mutable_raw_track_key() {
  
  return _impl_.raw_track_key_.Mutable(GetArenaForAllocation());
}
inline std::string* RawTrackTemplate::release_raw_track_key() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.RawTrackTemplate.raw_track_key)
  return _impl_.raw_track_key_.Release();
}
inline void RawTrackTemplate::set_allocated_raw_track_key(std::string* raw_track_key) {
  if (raw_track_key != nullptr) {
    
  } else {
    
  }
  _impl_.raw_track_key_.SetAllocated(raw_track_key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.raw_track_key_.IsDefault()) {
    _impl_.raw_track_key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.RawTrackTemplate.raw_track_key)
}

// int64 first_pts_ns = 2;
inline void RawTrackTemplate::clear_first_pts_ns() {
  _impl_.first_pts_ns_ = int64_t{0};
}
inline int64_t RawTrackTemplate::_internal_first_pts_ns() const {
  return _impl_.first_pts_ns_;
}
inline int64_t RawTrackTemplate::first_pts_ns() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.RawTrackTemplate.first_pts_ns)
  return _internal_first_pts_ns();
}
inline void RawTrackTemplate::_internal_set_first_pts_ns(int64_t value) {
  
  _impl_.first_pts_ns_ = value;
}
inline void RawTrackTemplate::set_first_pts_ns(int64_t value) {
  _internal_set_first_pts_ns(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.RawTrackTemplate.first_pts_ns)
}

// int64 last_pts_ns = 3;
inline void RawTrackTemplate::clear_last_pts_ns() {
  _impl_.last_pts_ns_ = int64_t{0};
}
inline int64_t RawTrackTemplate::_internal_last_pts_ns() const {
  return _impl_.last_pts_ns_;
}
inline int64_t RawTrackTemplate::last_pts_ns() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.RawTrackTemplate.last_pts_ns)
  return _internal_last_pts_ns();
}
inline void RawTrackTemplate::_internal_set_last_pts_ns(int64_t value) {
  
  _impl_.last_pts_ns_ = value;
}
inline void RawTrackTemplate::set_last_pts_ns(int64_t value) {
  _internal_set_last_pts_ns(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.RawTrackTemplate.last_pts_ns)
}

// int64 observation_count = 4;
inline void RawTrackTemplate::clear_observation_count() {
  _impl_.observation_count_ = int64_t{0};
}
inline int64_t RawTrackTemplate::_internal_observation_count() const {
  return _impl_.observation_count_;
}
inline int64_t RawTrackTemplate::observation_count() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.RawTrackTemplate.observation_count)
  return _internal_observation_count();
}
inline void RawTrackTemplate::_internal_set_observation_count(int64_t value) {
  
  _impl_.observation_count_ = value;
}
inline void RawTrackTemplate::set_observation_count(int64_t value) {
  _internal_set_observation_count(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.RawTrackTemplate.observation_count)
}

// int64 eligible_observation_count = 5;
inline void RawTrackTemplate::clear_eligible_observation_count() {
  _impl_.eligible_observation_count_ = int64_t{0};
}
inline int64_t RawTrackTemplate::_internal_eligible_observation_count() const {
  return _impl_.eligible_observation_count_;
}
inline int64_t RawTrackTemplate::eligible_observation_count() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.RawTrackTemplate.eligible_observation_count)
  return _internal_eligible_observation_count();
}
inline void RawTrackTemplate::_internal_set_eligible_observation_count(int64_t value) {
  
  _impl_.eligible_observation_count_ = value;
}
inline void RawTrackTemplate::set_eligible_observation_count(int64_t value) {
  _internal_set_eligible_observation_count(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.RawTrackTemplate.eligible_observation_count)
}

// repeated float template_embedding = 6;
inline int RawTrackTemplate::_internal_template_embedding_size() const {
  return _impl_.template_embedding_.size();
}
inline int RawTrackTemplate::template_embedding_size() const {
  return _internal_template_embedding_size();
}
inline void RawTrackTemplate::clear_template_embedding() {
  _impl_.template_embedding_.Clear();
}
inline float RawTrackTemplate::_internal_template_embedding(int index) const {
  return _impl_.template_embedding_.Get(index);
}
inline float RawTrackTemplate::template_embedding(int index) const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.RawTrackTemplate.template_embedding)
  return _internal_template_embedding(index);
}
inline void RawTrackTemplate::set_template_embedding(int index, float value) {
  _impl_.template_embedding_.Set(index, value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.RawTrackTemplate.template_embedding)
}
inline void RawTrackTemplate::_internal_add_template_embedding(float value) {
  _impl_.template_embedding_.Add(value);
}
inline void RawTrackTemplate::add_template_embedding(float value) {
  _internal_add_template_embedding(value);
  // @@protoc_insertion_point(field_add:mergenvision.video.v1.RawTrackTemplate.template_embedding)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
RawTrackTemplate::_internal_template_embedding() const {
  return _impl_.template_embedding_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
RawTrackTemplate::template_embedding() const {
  // @@protoc_insertion_point(field_list:mergenvision.video.v1.RawTrackTemplate.template_embedding)
  return _internal_template_embedding();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
RawTrackTemplate::_internal_mutable_template_embedding() {
  return &_impl_.template_embedding_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
RawTrackTemplate::mutable_template_embedding() {
  // @@protoc_insertion_point(field_mutable_list:mergenvision.video.v1.RawTrackTemplate.template_embedding)
  return _internal_mutable_template_embedding();
}

// float template_quality = 7;
inline void RawTrackTemplate::clear_template_quality() {
  _impl_.template_quality_ = 0;
}
inline float RawTrackTemplate::_internal_template_quality() const {
  return _impl_.template_quality_;
}
inline float RawTrackTemplate::template_quality() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.RawTrackTemplate.template_quality)
  return _internal_template_quality();
}
inline void RawTrackTemplate::_internal_set_template_quality(float value) {
  
  _impl_.template_quality_ = value;
}
inline void RawTrackTemplate::set_template_quality(float value) {
  _internal_set_template_quality(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.RawTrackTemplate.template_quality)
}

// string representative_crop_relative_key = 8;
inline void RawTrackTemplate::clear_representative_crop_relative_key() {
  _impl_.representative_crop_relative_key_.ClearToEmpty();
}
inline const std::string& RawTrackTemplate::representative_crop_relative_key() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.RawTrackTemplate.representative_crop_relative_key)
  return _internal_representative_crop_relative_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RawTrackTemplate::set_representative_crop_relative_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.representative_crop_relative_key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.RawTrackTemplate.representative_crop_relative_key)
}
inline std::string* RawTrackTemplate::mutable_representative_crop_relative_key() {
  std::string* _s = _internal_mutable_representative_crop_relative_key();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.RawTrackTemplate.representative_crop_relative_key)
  return _s;
}
inline const std::string& RawTrackTemplate::_internal_representative_crop_relative_key() const {
  return _impl_.representative_crop_relative_key_.Get();
}
inline void RawTrackTemplate::_internal_set_representative_crop_relative_key(const std::string& value) {
  
  _impl_.representative_crop_relative_key_.Set(value, GetArenaForAllocation());
}
inline std::string* RawTrackTemplate::_internal_mutable_representative_crop_relative_key() {
  
  return _impl_.representative_crop_relative_key_.Mutable(GetArenaForAllocation());
}
inline std::string* RawTrackTemplate::release_representative_crop_relative_key() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.RawTrackTemplate.representative_crop_relative_key)
  return _impl_.representative_crop_relative_key_.Release();
}
inline void RawTrackTemplate::set_allocated_representative_crop_relative_key(std::string* representative_crop_relative_key) {
  if (representative_crop_relative_key != nullptr) {
    
  } else {
    
  }
  _impl_.representative_crop_relative_key_.SetAllocated(representative_crop_relative_key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.representative_crop_relative_key_.IsDefault()) {
    _impl_.representative_crop_relative_key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.RawTrackTemplate.representative_crop_relative_key)
}

// int32 representative_x = 9;
inline void RawTrackTemplate::clear_representative_x() {
  _impl_.representative_x_ = 0;
}
inline int32_t RawTrackTemplate::_internal_representative_x() const {
  return _impl_.representative_x_;
}
inline int32_t RawTrackTemplate::representative_x() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.RawTrackTemplate.representative_x)
  return _internal_representative_x();
}
inline void RawTrackTemplate::_internal_set_representative_x(int32_t value) {
  
  _impl_.representative_x_ = value;
}
inline void RawTrackTemplate::set_representative_x(int32_t value) {
  _internal_set_representative_x(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.RawTrackTemplate.representative_x)
}

// int32 representative_y = 10;
inline void RawTrackTemplate::clear_representative_y() {
  _impl_.representative_y_ = 0;
}
inline int32_t RawTrackTemplate::_internal_representative_y() const {
  return _impl_.representative_y_;
}
inline int32_t RawTrackTemplate::representative_y() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.RawTrackTemplate.representative_y)
  return _internal_representative_y();
}
inline void RawTrackTemplate::_internal_set_representative_y(int32_t value) {
  
  _impl_.representative_y_ = value;
}
inline void RawTrackTemplate::set_representative_y(int32_t value) {
  _internal_set_representative_y(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.RawTrackTemplate.representative_y)
}

// int32 representative_width = 11;
inline void RawTrackTemplate::clear_representative_width() {
  _impl_.representative_width_ = 0;
}
inline int32_t RawTrackTemplate::_internal_representative_width() const {
  return _impl_.representative_width_;
}
inline int32_t RawTrackTemplate::representative_width() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.RawTrackTemplate.representative_width)
  return _internal_representative_width();
}
inline void RawTrackTemplate::_internal_set_representative_width(int32_t value) {
  
  _impl_.representative_width_ = value;
}
inline void RawTrackTemplate::set_representative_width(int32_t value) {
  _internal_set_representative_width(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.RawTrackTemplate.representative_width)
}

// int32 representative_height = 12;
inline void RawTrackTemplate::clear_representative_height() {
  _impl_.representative_height_ = 0;
}
inline int32_t RawTrackTemplate::_internal_representative_height() const {
  return _impl_.representative_height_;
}
inline int32_t RawTrackTemplate::representative_height() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.RawTrackTemplate.representative_height)
  return _internal_representative_height();
}
inline void RawTrackTemplate::_internal_set_representative_height(int32_t value) {
  
  _impl_.representative_height_ = value;
}
inline void RawTrackTemplate::set_representative_height(int32_t value) {
  _internal_set_representative_height(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.RawTrackTemplate.representative_height)
}

// int64 representative_pts_ns = 13;
inline void RawTrackTemplate::clear_representative_pts_ns() {
  _impl_.representative_pts_ns_ = int64_t{0};
}
inline int64_t RawTrackTemplate::_internal_representative_pts_ns() const {
  return _impl_.representative_pts_ns_;
}
inline int64_t RawTrackTemplate::representative_pts_ns() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.RawTrackTemplate.representative_pts_ns)
  return _internal_representative_pts_ns();
}
inline void RawTrackTemplate::_internal_set_representative_pts_ns(int64_t value) {
  
  _impl_.representative_pts_ns_ = value;
}
inline void RawTrackTemplate::set_representative_pts_ns(int64_t value) {
  _internal_set_representative_pts_ns(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.RawTrackTemplate.representative_pts_ns)
}

// int32 representative_ordinal = 14;
inline void RawTrackTemplate::clear_representative_ordinal() {
  _impl_.representative_ordinal_ = 0;
}
inline int32_t RawTrackTemplate::_internal_representative_ordinal() const {
  return _impl_.representative_ordinal_;
}
inline int32_t RawTrackTemplate::representative_ordinal() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.RawTrackTemplate.representative_ordinal)
  return _internal_representative_ordinal();
}
inline void RawTrackTemplate::_internal_set_representative_ordinal(int32_t value) {
  
  _impl_.representative_ordinal_ = value;
}
inline void RawTrackTemplate::set_representative_ordinal(int32_t value) {
  _internal_set_representative_ordinal(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.RawTrackTemplate.representative_ordinal)
}

// string no_crop_reason = 15;
inline void RawTrackTemplate::clear_no_crop_reason() {
  _impl_.no_crop_reason_.ClearToEmpty();
}
inline const std::string& RawTrackTemplate::no_crop_reason() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.RawTrackTemplate.no_crop_reason)
  return _internal_no_crop_reason();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RawTrackTemplate::set_no_crop_reason(ArgT0&& arg0, ArgT... args) {
 
 _impl_.no_crop_reason_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.RawTrackTemplate.no_crop_reason)
}
inline std::string* RawTrackTemplate::mutable_no_crop_reason() {
  std::string* _s = _internal_mutable_no_crop_reason();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.RawTrackTemplate.no_crop_reason)
  return _s;
}
inline const std::string& RawTrackTemplate::_internal_no_crop_reason() const {
  return _impl_.no_crop_reason_.Get();
}
inline void RawTrackTemplate::_internal_set_no_crop_reason(const std::string& value) {
  
  _impl_.no_crop_reason_.Set(value, GetArenaForAllocation());
}
inline std::string* RawTrackTemplate::_internal_mutable_no_crop_reason() {
  
  return _impl_.no_crop_reason_.Mutable(GetArenaForAllocation());
}
inline std::string* RawTrackTemplate::release_no_crop_reason() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.RawTrackTemplate.no_crop_reason)
  return _impl_.no_crop_reason_.Release();
}
inline void RawTrackTemplate::set_allocated_no_crop_reason(std::string* no_crop_reason) {
  if (no_crop_reason != nullptr) {
    
  } else {
    
  }
  _impl_.no_crop_reason_.SetAllocated(no_crop_reason, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.no_crop_reason_.IsDefault()) {
    _impl_.no_crop_reason_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.RawTrackTemplate.no_crop_reason)
}

// -------------------------------------------------------------------

// TrackTemplateFooter

// string job_id = 1;
inline void TrackTemplateFooter::clear_job_id() {
  _impl_.job_id_.ClearToEmpty();
}
inline const std::string& TrackTemplateFooter::job_id() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.TrackTemplateFooter.job_id)
  return _internal_job_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TrackTemplateFooter::set_job_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.job_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.TrackTemplateFooter.job_id)
}
inline std::string* TrackTemplateFooter::mutable_job_id() {
  std::string* _s = _internal_mutable_job_id();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.TrackTemplateFooter.job_id)
  return _s;
}
inline const std::string& TrackTemplateFooter::_internal_job_id() const {
  return _impl_.job_id_.Get();
}
inline void TrackTemplateFooter::_internal_set_job_id(const std::string& value) {
  
  _impl_.job_id_.Set(value, GetArenaForAllocation());
}
inline std::string* TrackTemplateFooter::_internal_mutable_job_id() {
  
  return _impl_.job_id_.Mutable(GetArenaForAllocation());
}
inline std::string* TrackTemplateFooter::release_job_id() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.TrackTemplateFooter.job_id)
  return _impl_.job_id_.Release();
}
inline void TrackTemplateFooter::set_allocated_job_id(std::string* job_id) {
  if (job_id != nullptr) {
    
  } else {
    
  }
  _impl_.job_id_.SetAllocated(job_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.job_id_.IsDefault()) {
    _impl_.job_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.TrackTemplateFooter.job_id)
}

// int64 sequence_no = 2;
inline void TrackTemplateFooter::clear_sequence_no() {
  _impl_.sequence_no_ = int64_t{0};
}
inline int64_t TrackTemplateFooter::_internal_sequence_no() const {
  return _impl_.sequence_no_;
}
inline int64_t TrackTemplateFooter::sequence_no() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.TrackTemplateFooter.sequence_no)
  return _internal_sequence_no();
}
inline void TrackTemplateFooter::_internal_set_sequence_no(int64_t value) {
  
  _impl_.sequence_no_ = value;
}
inline void TrackTemplateFooter::set_sequence_no(int64_t value) {
  _internal_set_sequence_no(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.TrackTemplateFooter.sequence_no)
}

// int64 template_count = 3;
inline void TrackTemplateFooter::clear_template_count() {
  _impl_.template_count_ = int64_t{0};
}
inline int64_t TrackTemplateFooter::_internal_template_count() const {
  return _impl_.template_count_;
}
inline int64_t TrackTemplateFooter::template_count() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.TrackTemplateFooter.template_count)
  return _internal_template_count();
}
inline void TrackTemplateFooter::_internal_set_template_count(int64_t value) {
  
  _impl_.template_count_ = value;
}
inline void TrackTemplateFooter::set_template_count(int64_t value) {
  _internal_set_template_count(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.TrackTemplateFooter.template_count)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace video
}  // namespace mergenvision

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_video_5ftrack_5ftemplate_5fv1_2eproto
