// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_observation_v1.proto

#include "video_observation_v1.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace mergenvision {
namespace video {
namespace v1 {
PROTOBUF_CONSTEXPR VideoObservationFrame::VideoObservationFrame(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.detections_)*/{}
  , /*decltype(_impl_.job_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.video_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.frame_index_)*/int64_t{0}
  , /*decltype(_impl_.source_pts_)*/int64_t{0}
  , /*decltype(_impl_.time_base_num_)*/int64_t{0}
  , /*decltype(_impl_.stream_index_)*/0
  , /*decltype(_impl_.display_width_)*/0
  , /*decltype(_impl_.time_base_den_)*/int64_t{0}
  , /*decltype(_impl_.pts_ns_)*/int64_t{0}
  , /*decltype(_impl_.display_height_)*/0
  , /*decltype(_impl_.rotation_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct VideoObservationFrameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VideoObservationFrameDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VideoObservationFrameDefaultTypeInternal() {}
  union {
    VideoObservationFrame _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VideoObservationFrameDefaultTypeInternal _VideoObservationFrame_default_instance_;
PROTOBUF_CONSTEXPR FaceDetection::FaceDetection(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.landmarks_)*/{}
  , /*decltype(_impl_.embedding_)*/{}
  , /*decltype(_impl_.detection_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.rejection_code_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.model_version_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.preprocess_version_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.raw_track_key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ordinal_)*/0
  , /*decltype(_impl_.x_)*/0
  , /*decltype(_impl_.y_)*/0
  , /*decltype(_impl_.width_)*/0
  , /*decltype(_impl_.height_)*/0
  , /*decltype(_impl_.detector_score_)*/0
  , /*decltype(_impl_.quality_score_)*/0
  , /*decltype(_impl_.tracking_eligible_)*/false
  , /*decltype(_impl_.recognition_eligible_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FaceDetectionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FaceDetectionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FaceDetectionDefaultTypeInternal() {}
  union {
    FaceDetection _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FaceDetectionDefaultTypeInternal _FaceDetection_default_instance_;
PROTOBUF_CONSTEXPR ObservationChunkFooter::ObservationChunkFooter(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.job_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sequence_no_)*/int64_t{0}
  , /*decltype(_impl_.frame_count_)*/int64_t{0}
  , /*decltype(_impl_.sha256_prefix_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ObservationChunkFooterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ObservationChunkFooterDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ObservationChunkFooterDefaultTypeInternal() {}
  union {
    ObservationChunkFooter _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ObservationChunkFooterDefaultTypeInternal _ObservationChunkFooter_default_instance_;
}  // namespace v1
}  // namespace video
}  // namespace mergenvision
static ::_pb::Metadata file_level_metadata_video_5fobservation_5fv1_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_video_5fobservation_5fv1_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_video_5fobservation_5fv1_2eproto = nullptr;

const uint32_t TableStruct_video_5fobservation_5fv1_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::VideoObservationFrame, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::VideoObservationFrame, _impl_.job_id_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::VideoObservationFrame, _impl_.video_id_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::VideoObservationFrame, _impl_.stream_index_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::VideoObservationFrame, _impl_.frame_index_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::VideoObservationFrame, _impl_.source_pts_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::VideoObservationFrame, _impl_.time_base_num_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::VideoObservationFrame, _impl_.time_base_den_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::VideoObservationFrame, _impl_.pts_ns_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::VideoObservationFrame, _impl_.display_width_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::VideoObservationFrame, _impl_.display_height_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::VideoObservationFrame, _impl_.rotation_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::VideoObservationFrame, _impl_.detections_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.detection_id_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.ordinal_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.x_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.y_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.width_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.height_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.landmarks_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.detector_score_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.quality_score_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.tracking_eligible_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.recognition_eligible_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.rejection_code_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.embedding_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.model_version_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.preprocess_version_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::FaceDetection, _impl_.raw_track_key_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::ObservationChunkFooter, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::ObservationChunkFooter, _impl_.job_id_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::ObservationChunkFooter, _impl_.sequence_no_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::ObservationChunkFooter, _impl_.frame_count_),
  PROTOBUF_FIELD_OFFSET(::mergenvision::video::v1::ObservationChunkFooter, _impl_.sha256_prefix_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::mergenvision::video::v1::VideoObservationFrame)},
  { 18, -1, -1, sizeof(::mergenvision::video::v1::FaceDetection)},
  { 40, -1, -1, sizeof(::mergenvision::video::v1::ObservationChunkFooter)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::mergenvision::video::v1::_VideoObservationFrame_default_instance_._instance,
  &::mergenvision::video::v1::_FaceDetection_default_instance_._instance,
  &::mergenvision::video::v1::_ObservationChunkFooter_default_instance_._instance,
};

const char descriptor_table_protodef_video_5fobservation_5fv1_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032video_observation_v1.proto\022\025mergenvisi"
  "on.video.v1\"\261\002\n\025VideoObservationFrame\022\016\n"
  "\006job_id\030\001 \001(\t\022\020\n\010video_id\030\002 \001(\t\022\024\n\014strea"
  "m_index\030\003 \001(\005\022\023\n\013frame_index\030\004 \001(\003\022\022\n\nso"
  "urce_pts\030\005 \001(\003\022\025\n\rtime_base_num\030\006 \001(\003\022\025\n"
  "\rtime_base_den\030\007 \001(\003\022\016\n\006pts_ns\030\010 \001(\003\022\025\n\r"
  "display_width\030\t \001(\005\022\026\n\016display_height\030\n "
  "\001(\005\022\020\n\010rotation\030\013 \001(\005\0228\n\ndetections\030\014 \003("
  "\0132$.mergenvision.video.v1.FaceDetection\""
  "\333\002\n\rFaceDetection\022\024\n\014detection_id\030\001 \001(\t\022"
  "\017\n\007ordinal\030\002 \001(\005\022\t\n\001x\030\003 \001(\005\022\t\n\001y\030\004 \001(\005\022\r"
  "\n\005width\030\005 \001(\005\022\016\n\006height\030\006 \001(\005\022\021\n\tlandmar"
  "ks\030\007 \003(\002\022\026\n\016detector_score\030\010 \001(\002\022\025\n\rqual"
  "ity_score\030\t \001(\002\022\031\n\021tracking_eligible\030\n \001"
  "(\010\022\034\n\024recognition_eligible\030\013 \001(\010\022\026\n\016reje"
  "ction_code\030\014 \001(\t\022\021\n\tembedding\030\r \003(\002\022\025\n\rm"
  "odel_version\030\016 \001(\t\022\032\n\022preprocess_version"
  "\030\017 \001(\t\022\025\n\rraw_track_key\030\020 \001(\t\"i\n\026Observa"
  "tionChunkFooter\022\016\n\006job_id\030\001 \001(\t\022\023\n\013seque"
  "nce_no\030\002 \001(\003\022\023\n\013frame_count\030\003 \001(\003\022\025\n\rsha"
  "256_prefix\030\004 \001(\003B4Z2github.com/mergenvis"
  "ion/backend/contracts/video/v1b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_video_5fobservation_5fv1_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_video_5fobservation_5fv1_2eproto = {
    false, false, 878, descriptor_table_protodef_video_5fobservation_5fv1_2eproto,
    "video_observation_v1.proto",
    &descriptor_table_video_5fobservation_5fv1_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_video_5fobservation_5fv1_2eproto::offsets,
    file_level_metadata_video_5fobservation_5fv1_2eproto, file_level_enum_descriptors_video_5fobservation_5fv1_2eproto,
    file_level_service_descriptors_video_5fobservation_5fv1_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_video_5fobservation_5fv1_2eproto_getter() {
  return &descriptor_table_video_5fobservation_5fv1_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_video_5fobservation_5fv1_2eproto(&descriptor_table_video_5fobservation_5fv1_2eproto);
namespace mergenvision {
namespace video {
namespace v1 {

// ===================================================================

class VideoObservationFrame::_Internal {
 public:
};

VideoObservationFrame::VideoObservationFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mergenvision.video.v1.VideoObservationFrame)
}
VideoObservationFrame::VideoObservationFrame(const VideoObservationFrame& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  VideoObservationFrame* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.detections_){from._impl_.detections_}
    , decltype(_impl_.job_id_){}
    , decltype(_impl_.video_id_){}
    , decltype(_impl_.frame_index_){}
    , decltype(_impl_.source_pts_){}
    , decltype(_impl_.time_base_num_){}
    , decltype(_impl_.stream_index_){}
    , decltype(_impl_.display_width_){}
    , decltype(_impl_.time_base_den_){}
    , decltype(_impl_.pts_ns_){}
    , decltype(_impl_.display_height_){}
    , decltype(_impl_.rotation_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_job_id().empty()) {
    _this->_impl_.job_id_.Set(from._internal_job_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.video_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.video_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_video_id().empty()) {
    _this->_impl_.video_id_.Set(from._internal_video_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.frame_index_, &from._impl_.frame_index_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.rotation_) -
    reinterpret_cast<char*>(&_impl_.frame_index_)) + sizeof(_impl_.rotation_));
  // @@protoc_insertion_point(copy_constructor:mergenvision.video.v1.VideoObservationFrame)
}

inline void VideoObservationFrame::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.detections_){arena}
    , decltype(_impl_.job_id_){}
    , decltype(_impl_.video_id_){}
    , decltype(_impl_.frame_index_){int64_t{0}}
    , decltype(_impl_.source_pts_){int64_t{0}}
    , decltype(_impl_.time_base_num_){int64_t{0}}
    , decltype(_impl_.stream_index_){0}
    , decltype(_impl_.display_width_){0}
    , decltype(_impl_.time_base_den_){int64_t{0}}
    , decltype(_impl_.pts_ns_){int64_t{0}}
    , decltype(_impl_.display_height_){0}
    , decltype(_impl_.rotation_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.video_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.video_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

VideoObservationFrame::~VideoObservationFrame() {
  // @@protoc_insertion_point(destructor:mergenvision.video.v1.VideoObservationFrame)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void VideoObservationFrame::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.detections_.~RepeatedPtrField();
  _impl_.job_id_.Destroy();
  _impl_.video_id_.Destroy();
}

void VideoObservationFrame::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VideoObservationFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:mergenvision.video.v1.VideoObservationFrame)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.detections_.Clear();
  _impl_.job_id_.ClearToEmpty();
  _impl_.video_id_.ClearToEmpty();
  ::memset(&_impl_.frame_index_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.rotation_) -
      reinterpret_cast<char*>(&_impl_.frame_index_)) + sizeof(_impl_.rotation_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VideoObservationFrame::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string job_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_job_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.VideoObservationFrame.job_id"));
        } else
          goto handle_unusual;
        continue;
      // string video_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_video_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.VideoObservationFrame.video_id"));
        } else
          goto handle_unusual;
        continue;
      // int32 stream_index = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.stream_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 frame_index = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.frame_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 source_pts = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.source_pts_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 time_base_num = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.time_base_num_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 time_base_den = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.time_base_den_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 pts_ns = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.pts_ns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 display_width = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.display_width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 display_height = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.display_height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 rotation = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 88)) {
          _impl_.rotation_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .mergenvision.video.v1.FaceDetection detections = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_detections(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<98>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VideoObservationFrame::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mergenvision.video.v1.VideoObservationFrame)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_job_id().data(), static_cast<int>(this->_internal_job_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.VideoObservationFrame.job_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_job_id(), target);
  }

  // string video_id = 2;
  if (!this->_internal_video_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_video_id().data(), static_cast<int>(this->_internal_video_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.VideoObservationFrame.video_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_video_id(), target);
  }

  // int32 stream_index = 3;
  if (this->_internal_stream_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_stream_index(), target);
  }

  // int64 frame_index = 4;
  if (this->_internal_frame_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_frame_index(), target);
  }

  // int64 source_pts = 5;
  if (this->_internal_source_pts() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(5, this->_internal_source_pts(), target);
  }

  // int64 time_base_num = 6;
  if (this->_internal_time_base_num() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(6, this->_internal_time_base_num(), target);
  }

  // int64 time_base_den = 7;
  if (this->_internal_time_base_den() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(7, this->_internal_time_base_den(), target);
  }

  // int64 pts_ns = 8;
  if (this->_internal_pts_ns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(8, this->_internal_pts_ns(), target);
  }

  // int32 display_width = 9;
  if (this->_internal_display_width() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(9, this->_internal_display_width(), target);
  }

  // int32 display_height = 10;
  if (this->_internal_display_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(10, this->_internal_display_height(), target);
  }

  // int32 rotation = 11;
  if (this->_internal_rotation() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(11, this->_internal_rotation(), target);
  }

  // repeated .mergenvision.video.v1.FaceDetection detections = 12;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_detections_size()); i < n; i++) {
    const auto& repfield = this->_internal_detections(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(12, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mergenvision.video.v1.VideoObservationFrame)
  return target;
}

size_t VideoObservationFrame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mergenvision.video.v1.VideoObservationFrame)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .mergenvision.video.v1.FaceDetection detections = 12;
  total_size += 1UL * this->_internal_detections_size();
  for (const auto& msg : this->_impl_.detections_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_job_id());
  }

  // string video_id = 2;
  if (!this->_internal_video_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_video_id());
  }

  // int64 frame_index = 4;
  if (this->_internal_frame_index() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_frame_index());
  }

  // int64 source_pts = 5;
  if (this->_internal_source_pts() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_source_pts());
  }

  // int64 time_base_num = 6;
  if (this->_internal_time_base_num() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_time_base_num());
  }

  // int32 stream_index = 3;
  if (this->_internal_stream_index() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_stream_index());
  }

  // int32 display_width = 9;
  if (this->_internal_display_width() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_display_width());
  }

  // int64 time_base_den = 7;
  if (this->_internal_time_base_den() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_time_base_den());
  }

  // int64 pts_ns = 8;
  if (this->_internal_pts_ns() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_pts_ns());
  }

  // int32 display_height = 10;
  if (this->_internal_display_height() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_display_height());
  }

  // int32 rotation = 11;
  if (this->_internal_rotation() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_rotation());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData VideoObservationFrame::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    VideoObservationFrame::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*VideoObservationFrame::GetClassData() const { return &_class_data_; }


void VideoObservationFrame::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<VideoObservationFrame*>(&to_msg);
  auto& from = static_cast<const VideoObservationFrame&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mergenvision.video.v1.VideoObservationFrame)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.detections_.MergeFrom(from._impl_.detections_);
  if (!from._internal_job_id().empty()) {
    _this->_internal_set_job_id(from._internal_job_id());
  }
  if (!from._internal_video_id().empty()) {
    _this->_internal_set_video_id(from._internal_video_id());
  }
  if (from._internal_frame_index() != 0) {
    _this->_internal_set_frame_index(from._internal_frame_index());
  }
  if (from._internal_source_pts() != 0) {
    _this->_internal_set_source_pts(from._internal_source_pts());
  }
  if (from._internal_time_base_num() != 0) {
    _this->_internal_set_time_base_num(from._internal_time_base_num());
  }
  if (from._internal_stream_index() != 0) {
    _this->_internal_set_stream_index(from._internal_stream_index());
  }
  if (from._internal_display_width() != 0) {
    _this->_internal_set_display_width(from._internal_display_width());
  }
  if (from._internal_time_base_den() != 0) {
    _this->_internal_set_time_base_den(from._internal_time_base_den());
  }
  if (from._internal_pts_ns() != 0) {
    _this->_internal_set_pts_ns(from._internal_pts_ns());
  }
  if (from._internal_display_height() != 0) {
    _this->_internal_set_display_height(from._internal_display_height());
  }
  if (from._internal_rotation() != 0) {
    _this->_internal_set_rotation(from._internal_rotation());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void VideoObservationFrame::CopyFrom(const VideoObservationFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mergenvision.video.v1.VideoObservationFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VideoObservationFrame::IsInitialized() const {
  return true;
}

void VideoObservationFrame::InternalSwap(VideoObservationFrame* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.detections_.InternalSwap(&other->_impl_.detections_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.job_id_, lhs_arena,
      &other->_impl_.job_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.video_id_, lhs_arena,
      &other->_impl_.video_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VideoObservationFrame, _impl_.rotation_)
      + sizeof(VideoObservationFrame::_impl_.rotation_)
      - PROTOBUF_FIELD_OFFSET(VideoObservationFrame, _impl_.frame_index_)>(
          reinterpret_cast<char*>(&_impl_.frame_index_),
          reinterpret_cast<char*>(&other->_impl_.frame_index_));
}

::PROTOBUF_NAMESPACE_ID::Metadata VideoObservationFrame::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_video_5fobservation_5fv1_2eproto_getter, &descriptor_table_video_5fobservation_5fv1_2eproto_once,
      file_level_metadata_video_5fobservation_5fv1_2eproto[0]);
}

// ===================================================================

class FaceDetection::_Internal {
 public:
};

FaceDetection::FaceDetection(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mergenvision.video.v1.FaceDetection)
}
FaceDetection::FaceDetection(const FaceDetection& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FaceDetection* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.landmarks_){from._impl_.landmarks_}
    , decltype(_impl_.embedding_){from._impl_.embedding_}
    , decltype(_impl_.detection_id_){}
    , decltype(_impl_.rejection_code_){}
    , decltype(_impl_.model_version_){}
    , decltype(_impl_.preprocess_version_){}
    , decltype(_impl_.raw_track_key_){}
    , decltype(_impl_.ordinal_){}
    , decltype(_impl_.x_){}
    , decltype(_impl_.y_){}
    , decltype(_impl_.width_){}
    , decltype(_impl_.height_){}
    , decltype(_impl_.detector_score_){}
    , decltype(_impl_.quality_score_){}
    , decltype(_impl_.tracking_eligible_){}
    , decltype(_impl_.recognition_eligible_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.detection_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.detection_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_detection_id().empty()) {
    _this->_impl_.detection_id_.Set(from._internal_detection_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.rejection_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rejection_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_rejection_code().empty()) {
    _this->_impl_.rejection_code_.Set(from._internal_rejection_code(), 
      _this->GetArenaForAllocation());
  }
  _impl_.model_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.model_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_model_version().empty()) {
    _this->_impl_.model_version_.Set(from._internal_model_version(), 
      _this->GetArenaForAllocation());
  }
  _impl_.preprocess_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.preprocess_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_preprocess_version().empty()) {
    _this->_impl_.preprocess_version_.Set(from._internal_preprocess_version(), 
      _this->GetArenaForAllocation());
  }
  _impl_.raw_track_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.raw_track_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_raw_track_key().empty()) {
    _this->_impl_.raw_track_key_.Set(from._internal_raw_track_key(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.ordinal_, &from._impl_.ordinal_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.recognition_eligible_) -
    reinterpret_cast<char*>(&_impl_.ordinal_)) + sizeof(_impl_.recognition_eligible_));
  // @@protoc_insertion_point(copy_constructor:mergenvision.video.v1.FaceDetection)
}

inline void FaceDetection::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.landmarks_){arena}
    , decltype(_impl_.embedding_){arena}
    , decltype(_impl_.detection_id_){}
    , decltype(_impl_.rejection_code_){}
    , decltype(_impl_.model_version_){}
    , decltype(_impl_.preprocess_version_){}
    , decltype(_impl_.raw_track_key_){}
    , decltype(_impl_.ordinal_){0}
    , decltype(_impl_.x_){0}
    , decltype(_impl_.y_){0}
    , decltype(_impl_.width_){0}
    , decltype(_impl_.height_){0}
    , decltype(_impl_.detector_score_){0}
    , decltype(_impl_.quality_score_){0}
    , decltype(_impl_.tracking_eligible_){false}
    , decltype(_impl_.recognition_eligible_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.detection_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.detection_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.rejection_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.rejection_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.model_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.model_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.preprocess_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.preprocess_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.raw_track_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.raw_track_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FaceDetection::~FaceDetection() {
  // @@protoc_insertion_point(destructor:mergenvision.video.v1.FaceDetection)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FaceDetection::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.landmarks_.~RepeatedField();
  _impl_.embedding_.~RepeatedField();
  _impl_.detection_id_.Destroy();
  _impl_.rejection_code_.Destroy();
  _impl_.model_version_.Destroy();
  _impl_.preprocess_version_.Destroy();
  _impl_.raw_track_key_.Destroy();
}

void FaceDetection::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FaceDetection::Clear() {
// @@protoc_insertion_point(message_clear_start:mergenvision.video.v1.FaceDetection)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.landmarks_.Clear();
  _impl_.embedding_.Clear();
  _impl_.detection_id_.ClearToEmpty();
  _impl_.rejection_code_.ClearToEmpty();
  _impl_.model_version_.ClearToEmpty();
  _impl_.preprocess_version_.ClearToEmpty();
  _impl_.raw_track_key_.ClearToEmpty();
  ::memset(&_impl_.ordinal_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.recognition_eligible_) -
      reinterpret_cast<char*>(&_impl_.ordinal_)) + sizeof(_impl_.recognition_eligible_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FaceDetection::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string detection_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_detection_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.FaceDetection.detection_id"));
        } else
          goto handle_unusual;
        continue;
      // int32 ordinal = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.ordinal_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 x = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 y = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 width = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 height = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated float landmarks = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_landmarks(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 61) {
          _internal_add_landmarks(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float detector_score = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 69)) {
          _impl_.detector_score_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float quality_score = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 77)) {
          _impl_.quality_score_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // bool tracking_eligible = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.tracking_eligible_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool recognition_eligible = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 88)) {
          _impl_.recognition_eligible_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string rejection_code = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          auto str = _internal_mutable_rejection_code();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.FaceDetection.rejection_code"));
        } else
          goto handle_unusual;
        continue;
      // repeated float embedding = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_embedding(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 109) {
          _internal_add_embedding(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // string model_version = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 114)) {
          auto str = _internal_mutable_model_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.FaceDetection.model_version"));
        } else
          goto handle_unusual;
        continue;
      // string preprocess_version = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 122)) {
          auto str = _internal_mutable_preprocess_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.FaceDetection.preprocess_version"));
        } else
          goto handle_unusual;
        continue;
      // string raw_track_key = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 130)) {
          auto str = _internal_mutable_raw_track_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.FaceDetection.raw_track_key"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FaceDetection::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mergenvision.video.v1.FaceDetection)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string detection_id = 1;
  if (!this->_internal_detection_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_detection_id().data(), static_cast<int>(this->_internal_detection_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.FaceDetection.detection_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_detection_id(), target);
  }

  // int32 ordinal = 2;
  if (this->_internal_ordinal() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_ordinal(), target);
  }

  // int32 x = 3;
  if (this->_internal_x() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_x(), target);
  }

  // int32 y = 4;
  if (this->_internal_y() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_y(), target);
  }

  // int32 width = 5;
  if (this->_internal_width() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_width(), target);
  }

  // int32 height = 6;
  if (this->_internal_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_height(), target);
  }

  // repeated float landmarks = 7;
  if (this->_internal_landmarks_size() > 0) {
    target = stream->WriteFixedPacked(7, _internal_landmarks(), target);
  }

  // float detector_score = 8;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_detector_score = this->_internal_detector_score();
  uint32_t raw_detector_score;
  memcpy(&raw_detector_score, &tmp_detector_score, sizeof(tmp_detector_score));
  if (raw_detector_score != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(8, this->_internal_detector_score(), target);
  }

  // float quality_score = 9;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_quality_score = this->_internal_quality_score();
  uint32_t raw_quality_score;
  memcpy(&raw_quality_score, &tmp_quality_score, sizeof(tmp_quality_score));
  if (raw_quality_score != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(9, this->_internal_quality_score(), target);
  }

  // bool tracking_eligible = 10;
  if (this->_internal_tracking_eligible() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(10, this->_internal_tracking_eligible(), target);
  }

  // bool recognition_eligible = 11;
  if (this->_internal_recognition_eligible() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(11, this->_internal_recognition_eligible(), target);
  }

  // string rejection_code = 12;
  if (!this->_internal_rejection_code().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_rejection_code().data(), static_cast<int>(this->_internal_rejection_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.FaceDetection.rejection_code");
    target = stream->WriteStringMaybeAliased(
        12, this->_internal_rejection_code(), target);
  }

  // repeated float embedding = 13;
  if (this->_internal_embedding_size() > 0) {
    target = stream->WriteFixedPacked(13, _internal_embedding(), target);
  }

  // string model_version = 14;
  if (!this->_internal_model_version().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_model_version().data(), static_cast<int>(this->_internal_model_version().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.FaceDetection.model_version");
    target = stream->WriteStringMaybeAliased(
        14, this->_internal_model_version(), target);
  }

  // string preprocess_version = 15;
  if (!this->_internal_preprocess_version().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_preprocess_version().data(), static_cast<int>(this->_internal_preprocess_version().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.FaceDetection.preprocess_version");
    target = stream->WriteStringMaybeAliased(
        15, this->_internal_preprocess_version(), target);
  }

  // string raw_track_key = 16;
  if (!this->_internal_raw_track_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_raw_track_key().data(), static_cast<int>(this->_internal_raw_track_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.FaceDetection.raw_track_key");
    target = stream->WriteStringMaybeAliased(
        16, this->_internal_raw_track_key(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mergenvision.video.v1.FaceDetection)
  return target;
}

size_t FaceDetection::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mergenvision.video.v1.FaceDetection)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float landmarks = 7;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_landmarks_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated float embedding = 13;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_embedding_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // string detection_id = 1;
  if (!this->_internal_detection_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_detection_id());
  }

  // string rejection_code = 12;
  if (!this->_internal_rejection_code().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_rejection_code());
  }

  // string model_version = 14;
  if (!this->_internal_model_version().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_model_version());
  }

  // string preprocess_version = 15;
  if (!this->_internal_preprocess_version().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_preprocess_version());
  }

  // string raw_track_key = 16;
  if (!this->_internal_raw_track_key().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_raw_track_key());
  }

  // int32 ordinal = 2;
  if (this->_internal_ordinal() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_ordinal());
  }

  // int32 x = 3;
  if (this->_internal_x() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_x());
  }

  // int32 y = 4;
  if (this->_internal_y() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_y());
  }

  // int32 width = 5;
  if (this->_internal_width() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_width());
  }

  // int32 height = 6;
  if (this->_internal_height() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_height());
  }

  // float detector_score = 8;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_detector_score = this->_internal_detector_score();
  uint32_t raw_detector_score;
  memcpy(&raw_detector_score, &tmp_detector_score, sizeof(tmp_detector_score));
  if (raw_detector_score != 0) {
    total_size += 1 + 4;
  }

  // float quality_score = 9;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_quality_score = this->_internal_quality_score();
  uint32_t raw_quality_score;
  memcpy(&raw_quality_score, &tmp_quality_score, sizeof(tmp_quality_score));
  if (raw_quality_score != 0) {
    total_size += 1 + 4;
  }

  // bool tracking_eligible = 10;
  if (this->_internal_tracking_eligible() != 0) {
    total_size += 1 + 1;
  }

  // bool recognition_eligible = 11;
  if (this->_internal_recognition_eligible() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FaceDetection::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FaceDetection::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FaceDetection::GetClassData() const { return &_class_data_; }


void FaceDetection::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FaceDetection*>(&to_msg);
  auto& from = static_cast<const FaceDetection&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mergenvision.video.v1.FaceDetection)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.landmarks_.MergeFrom(from._impl_.landmarks_);
  _this->_impl_.embedding_.MergeFrom(from._impl_.embedding_);
  if (!from._internal_detection_id().empty()) {
    _this->_internal_set_detection_id(from._internal_detection_id());
  }
  if (!from._internal_rejection_code().empty()) {
    _this->_internal_set_rejection_code(from._internal_rejection_code());
  }
  if (!from._internal_model_version().empty()) {
    _this->_internal_set_model_version(from._internal_model_version());
  }
  if (!from._internal_preprocess_version().empty()) {
    _this->_internal_set_preprocess_version(from._internal_preprocess_version());
  }
  if (!from._internal_raw_track_key().empty()) {
    _this->_internal_set_raw_track_key(from._internal_raw_track_key());
  }
  if (from._internal_ordinal() != 0) {
    _this->_internal_set_ordinal(from._internal_ordinal());
  }
  if (from._internal_x() != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  if (from._internal_y() != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  if (from._internal_width() != 0) {
    _this->_internal_set_width(from._internal_width());
  }
  if (from._internal_height() != 0) {
    _this->_internal_set_height(from._internal_height());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_detector_score = from._internal_detector_score();
  uint32_t raw_detector_score;
  memcpy(&raw_detector_score, &tmp_detector_score, sizeof(tmp_detector_score));
  if (raw_detector_score != 0) {
    _this->_internal_set_detector_score(from._internal_detector_score());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_quality_score = from._internal_quality_score();
  uint32_t raw_quality_score;
  memcpy(&raw_quality_score, &tmp_quality_score, sizeof(tmp_quality_score));
  if (raw_quality_score != 0) {
    _this->_internal_set_quality_score(from._internal_quality_score());
  }
  if (from._internal_tracking_eligible() != 0) {
    _this->_internal_set_tracking_eligible(from._internal_tracking_eligible());
  }
  if (from._internal_recognition_eligible() != 0) {
    _this->_internal_set_recognition_eligible(from._internal_recognition_eligible());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FaceDetection::CopyFrom(const FaceDetection& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mergenvision.video.v1.FaceDetection)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FaceDetection::IsInitialized() const {
  return true;
}

void FaceDetection::InternalSwap(FaceDetection* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.landmarks_.InternalSwap(&other->_impl_.landmarks_);
  _impl_.embedding_.InternalSwap(&other->_impl_.embedding_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.detection_id_, lhs_arena,
      &other->_impl_.detection_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.rejection_code_, lhs_arena,
      &other->_impl_.rejection_code_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.model_version_, lhs_arena,
      &other->_impl_.model_version_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.preprocess_version_, lhs_arena,
      &other->_impl_.preprocess_version_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.raw_track_key_, lhs_arena,
      &other->_impl_.raw_track_key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FaceDetection, _impl_.recognition_eligible_)
      + sizeof(FaceDetection::_impl_.recognition_eligible_)
      - PROTOBUF_FIELD_OFFSET(FaceDetection, _impl_.ordinal_)>(
          reinterpret_cast<char*>(&_impl_.ordinal_),
          reinterpret_cast<char*>(&other->_impl_.ordinal_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FaceDetection::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_video_5fobservation_5fv1_2eproto_getter, &descriptor_table_video_5fobservation_5fv1_2eproto_once,
      file_level_metadata_video_5fobservation_5fv1_2eproto[1]);
}

// ===================================================================

class ObservationChunkFooter::_Internal {
 public:
};

ObservationChunkFooter::ObservationChunkFooter(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mergenvision.video.v1.ObservationChunkFooter)
}
ObservationChunkFooter::ObservationChunkFooter(const ObservationChunkFooter& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ObservationChunkFooter* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.job_id_){}
    , decltype(_impl_.sequence_no_){}
    , decltype(_impl_.frame_count_){}
    , decltype(_impl_.sha256_prefix_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_job_id().empty()) {
    _this->_impl_.job_id_.Set(from._internal_job_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.sequence_no_, &from._impl_.sequence_no_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.sha256_prefix_) -
    reinterpret_cast<char*>(&_impl_.sequence_no_)) + sizeof(_impl_.sha256_prefix_));
  // @@protoc_insertion_point(copy_constructor:mergenvision.video.v1.ObservationChunkFooter)
}

inline void ObservationChunkFooter::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.job_id_){}
    , decltype(_impl_.sequence_no_){int64_t{0}}
    , decltype(_impl_.frame_count_){int64_t{0}}
    , decltype(_impl_.sha256_prefix_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ObservationChunkFooter::~ObservationChunkFooter() {
  // @@protoc_insertion_point(destructor:mergenvision.video.v1.ObservationChunkFooter)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ObservationChunkFooter::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.job_id_.Destroy();
}

void ObservationChunkFooter::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ObservationChunkFooter::Clear() {
// @@protoc_insertion_point(message_clear_start:mergenvision.video.v1.ObservationChunkFooter)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.job_id_.ClearToEmpty();
  ::memset(&_impl_.sequence_no_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.sha256_prefix_) -
      reinterpret_cast<char*>(&_impl_.sequence_no_)) + sizeof(_impl_.sha256_prefix_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ObservationChunkFooter::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string job_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_job_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mergenvision.video.v1.ObservationChunkFooter.job_id"));
        } else
          goto handle_unusual;
        continue;
      // int64 sequence_no = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.sequence_no_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 frame_count = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.frame_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 sha256_prefix = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.sha256_prefix_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ObservationChunkFooter::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mergenvision.video.v1.ObservationChunkFooter)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_job_id().data(), static_cast<int>(this->_internal_job_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mergenvision.video.v1.ObservationChunkFooter.job_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_job_id(), target);
  }

  // int64 sequence_no = 2;
  if (this->_internal_sequence_no() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_sequence_no(), target);
  }

  // int64 frame_count = 3;
  if (this->_internal_frame_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_frame_count(), target);
  }

  // int64 sha256_prefix = 4;
  if (this->_internal_sha256_prefix() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_sha256_prefix(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mergenvision.video.v1.ObservationChunkFooter)
  return target;
}

size_t ObservationChunkFooter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mergenvision.video.v1.ObservationChunkFooter)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_job_id());
  }

  // int64 sequence_no = 2;
  if (this->_internal_sequence_no() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_sequence_no());
  }

  // int64 frame_count = 3;
  if (this->_internal_frame_count() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_frame_count());
  }

  // int64 sha256_prefix = 4;
  if (this->_internal_sha256_prefix() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_sha256_prefix());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ObservationChunkFooter::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ObservationChunkFooter::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ObservationChunkFooter::GetClassData() const { return &_class_data_; }


void ObservationChunkFooter::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ObservationChunkFooter*>(&to_msg);
  auto& from = static_cast<const ObservationChunkFooter&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mergenvision.video.v1.ObservationChunkFooter)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_job_id().empty()) {
    _this->_internal_set_job_id(from._internal_job_id());
  }
  if (from._internal_sequence_no() != 0) {
    _this->_internal_set_sequence_no(from._internal_sequence_no());
  }
  if (from._internal_frame_count() != 0) {
    _this->_internal_set_frame_count(from._internal_frame_count());
  }
  if (from._internal_sha256_prefix() != 0) {
    _this->_internal_set_sha256_prefix(from._internal_sha256_prefix());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ObservationChunkFooter::CopyFrom(const ObservationChunkFooter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mergenvision.video.v1.ObservationChunkFooter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObservationChunkFooter::IsInitialized() const {
  return true;
}

void ObservationChunkFooter::InternalSwap(ObservationChunkFooter* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.job_id_, lhs_arena,
      &other->_impl_.job_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ObservationChunkFooter, _impl_.sha256_prefix_)
      + sizeof(ObservationChunkFooter::_impl_.sha256_prefix_)
      - PROTOBUF_FIELD_OFFSET(ObservationChunkFooter, _impl_.sequence_no_)>(
          reinterpret_cast<char*>(&_impl_.sequence_no_),
          reinterpret_cast<char*>(&other->_impl_.sequence_no_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ObservationChunkFooter::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_video_5fobservation_5fv1_2eproto_getter, &descriptor_table_video_5fobservation_5fv1_2eproto_once,
      file_level_metadata_video_5fobservation_5fv1_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace video
}  // namespace mergenvision
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mergenvision::video::v1::VideoObservationFrame*
Arena::CreateMaybeMessage< ::mergenvision::video::v1::VideoObservationFrame >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mergenvision::video::v1::VideoObservationFrame >(arena);
}
template<> PROTOBUF_NOINLINE ::mergenvision::video::v1::FaceDetection*
Arena::CreateMaybeMessage< ::mergenvision::video::v1::FaceDetection >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mergenvision::video::v1::FaceDetection >(arena);
}
template<> PROTOBUF_NOINLINE ::mergenvision::video::v1::ObservationChunkFooter*
Arena::CreateMaybeMessage< ::mergenvision::video::v1::ObservationChunkFooter >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mergenvision::video::v1::ObservationChunkFooter >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
