// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_observation_v1.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_video_5fobservation_5fv1_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_video_5fobservation_5fv1_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_video_5fobservation_5fv1_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_video_5fobservation_5fv1_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_video_5fobservation_5fv1_2eproto;
namespace mergenvision {
namespace video {
namespace v1 {
class FaceDetection;
struct FaceDetectionDefaultTypeInternal;
extern FaceDetectionDefaultTypeInternal _FaceDetection_default_instance_;
class ObservationChunkFooter;
struct ObservationChunkFooterDefaultTypeInternal;
extern ObservationChunkFooterDefaultTypeInternal _ObservationChunkFooter_default_instance_;
class VideoObservationFrame;
struct VideoObservationFrameDefaultTypeInternal;
extern VideoObservationFrameDefaultTypeInternal _VideoObservationFrame_default_instance_;
}  // namespace v1
}  // namespace video
}  // namespace mergenvision
PROTOBUF_NAMESPACE_OPEN
template<> ::mergenvision::video::v1::FaceDetection* Arena::CreateMaybeMessage<::mergenvision::video::v1::FaceDetection>(Arena*);
template<> ::mergenvision::video::v1::ObservationChunkFooter* Arena::CreateMaybeMessage<::mergenvision::video::v1::ObservationChunkFooter>(Arena*);
template<> ::mergenvision::video::v1::VideoObservationFrame* Arena::CreateMaybeMessage<::mergenvision::video::v1::VideoObservationFrame>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mergenvision {
namespace video {
namespace v1 {

// ===================================================================

class VideoObservationFrame final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mergenvision.video.v1.VideoObservationFrame) */ {
 public:
  inline VideoObservationFrame() : VideoObservationFrame(nullptr) {}
  ~VideoObservationFrame() override;
  explicit PROTOBUF_CONSTEXPR VideoObservationFrame(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VideoObservationFrame(const VideoObservationFrame& from);
  VideoObservationFrame(VideoObservationFrame&& from) noexcept
    : VideoObservationFrame() {
    *this = ::std::move(from);
  }

  inline VideoObservationFrame& operator=(const VideoObservationFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline VideoObservationFrame& operator=(VideoObservationFrame&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VideoObservationFrame& default_instance() {
    return *internal_default_instance();
  }
  static inline const VideoObservationFrame* internal_default_instance() {
    return reinterpret_cast<const VideoObservationFrame*>(
               &_VideoObservationFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(VideoObservationFrame& a, VideoObservationFrame& b) {
    a.Swap(&b);
  }
  inline void Swap(VideoObservationFrame* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VideoObservationFrame* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VideoObservationFrame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VideoObservationFrame>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VideoObservationFrame& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VideoObservationFrame& from) {
    VideoObservationFrame::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VideoObservationFrame* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mergenvision.video.v1.VideoObservationFrame";
  }
  protected:
  explicit VideoObservationFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDetectionsFieldNumber = 12,
    kJobIdFieldNumber = 1,
    kVideoIdFieldNumber = 2,
    kFrameIndexFieldNumber = 4,
    kSourcePtsFieldNumber = 5,
    kTimeBaseNumFieldNumber = 6,
    kStreamIndexFieldNumber = 3,
    kDisplayWidthFieldNumber = 9,
    kTimeBaseDenFieldNumber = 7,
    kPtsNsFieldNumber = 8,
    kDisplayHeightFieldNumber = 10,
    kRotationFieldNumber = 11,
  };
  // repeated .mergenvision.video.v1.FaceDetection detections = 12;
  int detections_size() const;
  private:
  int _internal_detections_size() const;
  public:
  void clear_detections();
  ::mergenvision::video::v1::FaceDetection* mutable_detections(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mergenvision::video::v1::FaceDetection >*
      mutable_detections();
  private:
  const ::mergenvision::video::v1::FaceDetection& _internal_detections(int index) const;
  ::mergenvision::video::v1::FaceDetection* _internal_add_detections();
  public:
  const ::mergenvision::video::v1::FaceDetection& detections(int index) const;
  ::mergenvision::video::v1::FaceDetection* add_detections();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mergenvision::video::v1::FaceDetection >&
      detections() const;

  // string job_id = 1;
  void clear_job_id();
  const std::string& job_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_job_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_job_id();
  PROTOBUF_NODISCARD std::string* release_job_id();
  void set_allocated_job_id(std::string* job_id);
  private:
  const std::string& _internal_job_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_job_id(const std::string& value);
  std::string* _internal_mutable_job_id();
  public:

  // string video_id = 2;
  void clear_video_id();
  const std::string& video_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_video_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_video_id();
  PROTOBUF_NODISCARD std::string* release_video_id();
  void set_allocated_video_id(std::string* video_id);
  private:
  const std::string& _internal_video_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_video_id(const std::string& value);
  std::string* _internal_mutable_video_id();
  public:

  // int64 frame_index = 4;
  void clear_frame_index();
  int64_t frame_index() const;
  void set_frame_index(int64_t value);
  private:
  int64_t _internal_frame_index() const;
  void _internal_set_frame_index(int64_t value);
  public:

  // int64 source_pts = 5;
  void clear_source_pts();
  int64_t source_pts() const;
  void set_source_pts(int64_t value);
  private:
  int64_t _internal_source_pts() const;
  void _internal_set_source_pts(int64_t value);
  public:

  // int64 time_base_num = 6;
  void clear_time_base_num();
  int64_t time_base_num() const;
  void set_time_base_num(int64_t value);
  private:
  int64_t _internal_time_base_num() const;
  void _internal_set_time_base_num(int64_t value);
  public:

  // int32 stream_index = 3;
  void clear_stream_index();
  int32_t stream_index() const;
  void set_stream_index(int32_t value);
  private:
  int32_t _internal_stream_index() const;
  void _internal_set_stream_index(int32_t value);
  public:

  // int32 display_width = 9;
  void clear_display_width();
  int32_t display_width() const;
  void set_display_width(int32_t value);
  private:
  int32_t _internal_display_width() const;
  void _internal_set_display_width(int32_t value);
  public:

  // int64 time_base_den = 7;
  void clear_time_base_den();
  int64_t time_base_den() const;
  void set_time_base_den(int64_t value);
  private:
  int64_t _internal_time_base_den() const;
  void _internal_set_time_base_den(int64_t value);
  public:

  // int64 pts_ns = 8;
  void clear_pts_ns();
  int64_t pts_ns() const;
  void set_pts_ns(int64_t value);
  private:
  int64_t _internal_pts_ns() const;
  void _internal_set_pts_ns(int64_t value);
  public:

  // int32 display_height = 10;
  void clear_display_height();
  int32_t display_height() const;
  void set_display_height(int32_t value);
  private:
  int32_t _internal_display_height() const;
  void _internal_set_display_height(int32_t value);
  public:

  // int32 rotation = 11;
  void clear_rotation();
  int32_t rotation() const;
  void set_rotation(int32_t value);
  private:
  int32_t _internal_rotation() const;
  void _internal_set_rotation(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:mergenvision.video.v1.VideoObservationFrame)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mergenvision::video::v1::FaceDetection > detections_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr job_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr video_id_;
    int64_t frame_index_;
    int64_t source_pts_;
    int64_t time_base_num_;
    int32_t stream_index_;
    int32_t display_width_;
    int64_t time_base_den_;
    int64_t pts_ns_;
    int32_t display_height_;
    int32_t rotation_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5fobservation_5fv1_2eproto;
};
// -------------------------------------------------------------------

class FaceDetection final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mergenvision.video.v1.FaceDetection) */ {
 public:
  inline FaceDetection() : FaceDetection(nullptr) {}
  ~FaceDetection() override;
  explicit PROTOBUF_CONSTEXPR FaceDetection(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FaceDetection(const FaceDetection& from);
  FaceDetection(FaceDetection&& from) noexcept
    : FaceDetection() {
    *this = ::std::move(from);
  }

  inline FaceDetection& operator=(const FaceDetection& from) {
    CopyFrom(from);
    return *this;
  }
  inline FaceDetection& operator=(FaceDetection&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FaceDetection& default_instance() {
    return *internal_default_instance();
  }
  static inline const FaceDetection* internal_default_instance() {
    return reinterpret_cast<const FaceDetection*>(
               &_FaceDetection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FaceDetection& a, FaceDetection& b) {
    a.Swap(&b);
  }
  inline void Swap(FaceDetection* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FaceDetection* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FaceDetection* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FaceDetection>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FaceDetection& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FaceDetection& from) {
    FaceDetection::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FaceDetection* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mergenvision.video.v1.FaceDetection";
  }
  protected:
  explicit FaceDetection(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLandmarksFieldNumber = 7,
    kEmbeddingFieldNumber = 13,
    kDetectionIdFieldNumber = 1,
    kRejectionCodeFieldNumber = 12,
    kModelVersionFieldNumber = 14,
    kPreprocessVersionFieldNumber = 15,
    kRawTrackKeyFieldNumber = 16,
    kOrdinalFieldNumber = 2,
    kXFieldNumber = 3,
    kYFieldNumber = 4,
    kWidthFieldNumber = 5,
    kHeightFieldNumber = 6,
    kDetectorScoreFieldNumber = 8,
    kQualityScoreFieldNumber = 9,
    kTrackingEligibleFieldNumber = 10,
    kRecognitionEligibleFieldNumber = 11,
  };
  // repeated float landmarks = 7;
  int landmarks_size() const;
  private:
  int _internal_landmarks_size() const;
  public:
  void clear_landmarks();
  private:
  float _internal_landmarks(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_landmarks() const;
  void _internal_add_landmarks(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_landmarks();
  public:
  float landmarks(int index) const;
  void set_landmarks(int index, float value);
  void add_landmarks(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      landmarks() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_landmarks();

  // repeated float embedding = 13;
  int embedding_size() const;
  private:
  int _internal_embedding_size() const;
  public:
  void clear_embedding();
  private:
  float _internal_embedding(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_embedding() const;
  void _internal_add_embedding(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_embedding();
  public:
  float embedding(int index) const;
  void set_embedding(int index, float value);
  void add_embedding(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      embedding() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_embedding();

  // string detection_id = 1;
  void clear_detection_id();
  const std::string& detection_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_detection_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_detection_id();
  PROTOBUF_NODISCARD std::string* release_detection_id();
  void set_allocated_detection_id(std::string* detection_id);
  private:
  const std::string& _internal_detection_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_detection_id(const std::string& value);
  std::string* _internal_mutable_detection_id();
  public:

  // string rejection_code = 12;
  void clear_rejection_code();
  const std::string& rejection_code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_rejection_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_rejection_code();
  PROTOBUF_NODISCARD std::string* release_rejection_code();
  void set_allocated_rejection_code(std::string* rejection_code);
  private:
  const std::string& _internal_rejection_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_rejection_code(const std::string& value);
  std::string* _internal_mutable_rejection_code();
  public:

  // string model_version = 14;
  void clear_model_version();
  const std::string& model_version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_model_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_model_version();
  PROTOBUF_NODISCARD std::string* release_model_version();
  void set_allocated_model_version(std::string* model_version);
  private:
  const std::string& _internal_model_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_model_version(const std::string& value);
  std::string* _internal_mutable_model_version();
  public:

  // string preprocess_version = 15;
  void clear_preprocess_version();
  const std::string& preprocess_version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_preprocess_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_preprocess_version();
  PROTOBUF_NODISCARD std::string* release_preprocess_version();
  void set_allocated_preprocess_version(std::string* preprocess_version);
  private:
  const std::string& _internal_preprocess_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_preprocess_version(const std::string& value);
  std::string* _internal_mutable_preprocess_version();
  public:

  // string raw_track_key = 16;
  void clear_raw_track_key();
  const std::string& raw_track_key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_raw_track_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_raw_track_key();
  PROTOBUF_NODISCARD std::string* release_raw_track_key();
  void set_allocated_raw_track_key(std::string* raw_track_key);
  private:
  const std::string& _internal_raw_track_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_raw_track_key(const std::string& value);
  std::string* _internal_mutable_raw_track_key();
  public:

  // int32 ordinal = 2;
  void clear_ordinal();
  int32_t ordinal() const;
  void set_ordinal(int32_t value);
  private:
  int32_t _internal_ordinal() const;
  void _internal_set_ordinal(int32_t value);
  public:

  // int32 x = 3;
  void clear_x();
  int32_t x() const;
  void set_x(int32_t value);
  private:
  int32_t _internal_x() const;
  void _internal_set_x(int32_t value);
  public:

  // int32 y = 4;
  void clear_y();
  int32_t y() const;
  void set_y(int32_t value);
  private:
  int32_t _internal_y() const;
  void _internal_set_y(int32_t value);
  public:

  // int32 width = 5;
  void clear_width();
  int32_t width() const;
  void set_width(int32_t value);
  private:
  int32_t _internal_width() const;
  void _internal_set_width(int32_t value);
  public:

  // int32 height = 6;
  void clear_height();
  int32_t height() const;
  void set_height(int32_t value);
  private:
  int32_t _internal_height() const;
  void _internal_set_height(int32_t value);
  public:

  // float detector_score = 8;
  void clear_detector_score();
  float detector_score() const;
  void set_detector_score(float value);
  private:
  float _internal_detector_score() const;
  void _internal_set_detector_score(float value);
  public:

  // float quality_score = 9;
  void clear_quality_score();
  float quality_score() const;
  void set_quality_score(float value);
  private:
  float _internal_quality_score() const;
  void _internal_set_quality_score(float value);
  public:

  // bool tracking_eligible = 10;
  void clear_tracking_eligible();
  bool tracking_eligible() const;
  void set_tracking_eligible(bool value);
  private:
  bool _internal_tracking_eligible() const;
  void _internal_set_tracking_eligible(bool value);
  public:

  // bool recognition_eligible = 11;
  void clear_recognition_eligible();
  bool recognition_eligible() const;
  void set_recognition_eligible(bool value);
  private:
  bool _internal_recognition_eligible() const;
  void _internal_set_recognition_eligible(bool value);
  public:

  // @@protoc_insertion_point(class_scope:mergenvision.video.v1.FaceDetection)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > landmarks_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > embedding_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr detection_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rejection_code_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr model_version_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr preprocess_version_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr raw_track_key_;
    int32_t ordinal_;
    int32_t x_;
    int32_t y_;
    int32_t width_;
    int32_t height_;
    float detector_score_;
    float quality_score_;
    bool tracking_eligible_;
    bool recognition_eligible_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5fobservation_5fv1_2eproto;
};
// -------------------------------------------------------------------

class ObservationChunkFooter final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mergenvision.video.v1.ObservationChunkFooter) */ {
 public:
  inline ObservationChunkFooter() : ObservationChunkFooter(nullptr) {}
  ~ObservationChunkFooter() override;
  explicit PROTOBUF_CONSTEXPR ObservationChunkFooter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ObservationChunkFooter(const ObservationChunkFooter& from);
  ObservationChunkFooter(ObservationChunkFooter&& from) noexcept
    : ObservationChunkFooter() {
    *this = ::std::move(from);
  }

  inline ObservationChunkFooter& operator=(const ObservationChunkFooter& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObservationChunkFooter& operator=(ObservationChunkFooter&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObservationChunkFooter& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObservationChunkFooter* internal_default_instance() {
    return reinterpret_cast<const ObservationChunkFooter*>(
               &_ObservationChunkFooter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ObservationChunkFooter& a, ObservationChunkFooter& b) {
    a.Swap(&b);
  }
  inline void Swap(ObservationChunkFooter* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObservationChunkFooter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ObservationChunkFooter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ObservationChunkFooter>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ObservationChunkFooter& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ObservationChunkFooter& from) {
    ObservationChunkFooter::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObservationChunkFooter* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mergenvision.video.v1.ObservationChunkFooter";
  }
  protected:
  explicit ObservationChunkFooter(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJobIdFieldNumber = 1,
    kSequenceNoFieldNumber = 2,
    kFrameCountFieldNumber = 3,
    kSha256PrefixFieldNumber = 4,
  };
  // string job_id = 1;
  void clear_job_id();
  const std::string& job_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_job_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_job_id();
  PROTOBUF_NODISCARD std::string* release_job_id();
  void set_allocated_job_id(std::string* job_id);
  private:
  const std::string& _internal_job_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_job_id(const std::string& value);
  std::string* _internal_mutable_job_id();
  public:

  // int64 sequence_no = 2;
  void clear_sequence_no();
  int64_t sequence_no() const;
  void set_sequence_no(int64_t value);
  private:
  int64_t _internal_sequence_no() const;
  void _internal_set_sequence_no(int64_t value);
  public:

  // int64 frame_count = 3;
  void clear_frame_count();
  int64_t frame_count() const;
  void set_frame_count(int64_t value);
  private:
  int64_t _internal_frame_count() const;
  void _internal_set_frame_count(int64_t value);
  public:

  // int64 sha256_prefix = 4;
  void clear_sha256_prefix();
  int64_t sha256_prefix() const;
  void set_sha256_prefix(int64_t value);
  private:
  int64_t _internal_sha256_prefix() const;
  void _internal_set_sha256_prefix(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:mergenvision.video.v1.ObservationChunkFooter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr job_id_;
    int64_t sequence_no_;
    int64_t frame_count_;
    int64_t sha256_prefix_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5fobservation_5fv1_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VideoObservationFrame

// string job_id = 1;
inline void VideoObservationFrame::clear_job_id() {
  _impl_.job_id_.ClearToEmpty();
}
inline const std::string& VideoObservationFrame::job_id() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.VideoObservationFrame.job_id)
  return _internal_job_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VideoObservationFrame::set_job_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.job_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.VideoObservationFrame.job_id)
}
inline std::string* VideoObservationFrame::mutable_job_id() {
  std::string* _s = _internal_mutable_job_id();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.VideoObservationFrame.job_id)
  return _s;
}
inline const std::string& VideoObservationFrame::_internal_job_id() const {
  return _impl_.job_id_.Get();
}
inline void VideoObservationFrame::_internal_set_job_id(const std::string& value) {
  
  _impl_.job_id_.Set(value, GetArenaForAllocation());
}
inline std::string* VideoObservationFrame::_internal_mutable_job_id() {
  
  return _impl_.job_id_.Mutable(GetArenaForAllocation());
}
inline std::string* VideoObservationFrame::release_job_id() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.VideoObservationFrame.job_id)
  return _impl_.job_id_.Release();
}
inline void VideoObservationFrame::set_allocated_job_id(std::string* job_id) {
  if (job_id != nullptr) {
    
  } else {
    
  }
  _impl_.job_id_.SetAllocated(job_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.job_id_.IsDefault()) {
    _impl_.job_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.VideoObservationFrame.job_id)
}

// string video_id = 2;
inline void VideoObservationFrame::clear_video_id() {
  _impl_.video_id_.ClearToEmpty();
}
inline const std::string& VideoObservationFrame::video_id() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.VideoObservationFrame.video_id)
  return _internal_video_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VideoObservationFrame::set_video_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.video_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.VideoObservationFrame.video_id)
}
inline std::string* VideoObservationFrame::mutable_video_id() {
  std::string* _s = _internal_mutable_video_id();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.VideoObservationFrame.video_id)
  return _s;
}
inline const std::string& VideoObservationFrame::_internal_video_id() const {
  return _impl_.video_id_.Get();
}
inline void VideoObservationFrame::_internal_set_video_id(const std::string& value) {
  
  _impl_.video_id_.Set(value, GetArenaForAllocation());
}
inline std::string* VideoObservationFrame::_internal_mutable_video_id() {
  
  return _impl_.video_id_.Mutable(GetArenaForAllocation());
}
inline std::string* VideoObservationFrame::release_video_id() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.VideoObservationFrame.video_id)
  return _impl_.video_id_.Release();
}
inline void VideoObservationFrame::set_allocated_video_id(std::string* video_id) {
  if (video_id != nullptr) {
    
  } else {
    
  }
  _impl_.video_id_.SetAllocated(video_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.video_id_.IsDefault()) {
    _impl_.video_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.VideoObservationFrame.video_id)
}

// int32 stream_index = 3;
inline void VideoObservationFrame::clear_stream_index() {
  _impl_.stream_index_ = 0;
}
inline int32_t VideoObservationFrame::_internal_stream_index() const {
  return _impl_.stream_index_;
}
inline int32_t VideoObservationFrame::stream_index() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.VideoObservationFrame.stream_index)
  return _internal_stream_index();
}
inline void VideoObservationFrame::_internal_set_stream_index(int32_t value) {
  
  _impl_.stream_index_ = value;
}
inline void VideoObservationFrame::set_stream_index(int32_t value) {
  _internal_set_stream_index(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.VideoObservationFrame.stream_index)
}

// int64 frame_index = 4;
inline void VideoObservationFrame::clear_frame_index() {
  _impl_.frame_index_ = int64_t{0};
}
inline int64_t VideoObservationFrame::_internal_frame_index() const {
  return _impl_.frame_index_;
}
inline int64_t VideoObservationFrame::frame_index() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.VideoObservationFrame.frame_index)
  return _internal_frame_index();
}
inline void VideoObservationFrame::_internal_set_frame_index(int64_t value) {
  
  _impl_.frame_index_ = value;
}
inline void VideoObservationFrame::set_frame_index(int64_t value) {
  _internal_set_frame_index(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.VideoObservationFrame.frame_index)
}

// int64 source_pts = 5;
inline void VideoObservationFrame::clear_source_pts() {
  _impl_.source_pts_ = int64_t{0};
}
inline int64_t VideoObservationFrame::_internal_source_pts() const {
  return _impl_.source_pts_;
}
inline int64_t VideoObservationFrame::source_pts() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.VideoObservationFrame.source_pts)
  return _internal_source_pts();
}
inline void VideoObservationFrame::_internal_set_source_pts(int64_t value) {
  
  _impl_.source_pts_ = value;
}
inline void VideoObservationFrame::set_source_pts(int64_t value) {
  _internal_set_source_pts(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.VideoObservationFrame.source_pts)
}

// int64 time_base_num = 6;
inline void VideoObservationFrame::clear_time_base_num() {
  _impl_.time_base_num_ = int64_t{0};
}
inline int64_t VideoObservationFrame::_internal_time_base_num() const {
  return _impl_.time_base_num_;
}
inline int64_t VideoObservationFrame::time_base_num() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.VideoObservationFrame.time_base_num)
  return _internal_time_base_num();
}
inline void VideoObservationFrame::_internal_set_time_base_num(int64_t value) {
  
  _impl_.time_base_num_ = value;
}
inline void VideoObservationFrame::set_time_base_num(int64_t value) {
  _internal_set_time_base_num(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.VideoObservationFrame.time_base_num)
}

// int64 time_base_den = 7;
inline void VideoObservationFrame::clear_time_base_den() {
  _impl_.time_base_den_ = int64_t{0};
}
inline int64_t VideoObservationFrame::_internal_time_base_den() const {
  return _impl_.time_base_den_;
}
inline int64_t VideoObservationFrame::time_base_den() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.VideoObservationFrame.time_base_den)
  return _internal_time_base_den();
}
inline void VideoObservationFrame::_internal_set_time_base_den(int64_t value) {
  
  _impl_.time_base_den_ = value;
}
inline void VideoObservationFrame::set_time_base_den(int64_t value) {
  _internal_set_time_base_den(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.VideoObservationFrame.time_base_den)
}

// int64 pts_ns = 8;
inline void VideoObservationFrame::clear_pts_ns() {
  _impl_.pts_ns_ = int64_t{0};
}
inline int64_t VideoObservationFrame::_internal_pts_ns() const {
  return _impl_.pts_ns_;
}
inline int64_t VideoObservationFrame::pts_ns() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.VideoObservationFrame.pts_ns)
  return _internal_pts_ns();
}
inline void VideoObservationFrame::_internal_set_pts_ns(int64_t value) {
  
  _impl_.pts_ns_ = value;
}
inline void VideoObservationFrame::set_pts_ns(int64_t value) {
  _internal_set_pts_ns(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.VideoObservationFrame.pts_ns)
}

// int32 display_width = 9;
inline void VideoObservationFrame::clear_display_width() {
  _impl_.display_width_ = 0;
}
inline int32_t VideoObservationFrame::_internal_display_width() const {
  return _impl_.display_width_;
}
inline int32_t VideoObservationFrame::display_width() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.VideoObservationFrame.display_width)
  return _internal_display_width();
}
inline void VideoObservationFrame::_internal_set_display_width(int32_t value) {
  
  _impl_.display_width_ = value;
}
inline void VideoObservationFrame::set_display_width(int32_t value) {
  _internal_set_display_width(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.VideoObservationFrame.display_width)
}

// int32 display_height = 10;
inline void VideoObservationFrame::clear_display_height() {
  _impl_.display_height_ = 0;
}
inline int32_t VideoObservationFrame::_internal_display_height() const {
  return _impl_.display_height_;
}
inline int32_t VideoObservationFrame::display_height() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.VideoObservationFrame.display_height)
  return _internal_display_height();
}
inline void VideoObservationFrame::_internal_set_display_height(int32_t value) {
  
  _impl_.display_height_ = value;
}
inline void VideoObservationFrame::set_display_height(int32_t value) {
  _internal_set_display_height(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.VideoObservationFrame.display_height)
}

// int32 rotation = 11;
inline void VideoObservationFrame::clear_rotation() {
  _impl_.rotation_ = 0;
}
inline int32_t VideoObservationFrame::_internal_rotation() const {
  return _impl_.rotation_;
}
inline int32_t VideoObservationFrame::rotation() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.VideoObservationFrame.rotation)
  return _internal_rotation();
}
inline void VideoObservationFrame::_internal_set_rotation(int32_t value) {
  
  _impl_.rotation_ = value;
}
inline void VideoObservationFrame::set_rotation(int32_t value) {
  _internal_set_rotation(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.VideoObservationFrame.rotation)
}

// repeated .mergenvision.video.v1.FaceDetection detections = 12;
inline int VideoObservationFrame::_internal_detections_size() const {
  return _impl_.detections_.size();
}
inline int VideoObservationFrame::detections_size() const {
  return _internal_detections_size();
}
inline void VideoObservationFrame::clear_detections() {
  _impl_.detections_.Clear();
}
inline ::mergenvision::video::v1::FaceDetection* VideoObservationFrame::mutable_detections(int index) {
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.VideoObservationFrame.detections)
  return _impl_.detections_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mergenvision::video::v1::FaceDetection >*
VideoObservationFrame::mutable_detections() {
  // @@protoc_insertion_point(field_mutable_list:mergenvision.video.v1.VideoObservationFrame.detections)
  return &_impl_.detections_;
}
inline const ::mergenvision::video::v1::FaceDetection& VideoObservationFrame::_internal_detections(int index) const {
  return _impl_.detections_.Get(index);
}
inline const ::mergenvision::video::v1::FaceDetection& VideoObservationFrame::detections(int index) const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.VideoObservationFrame.detections)
  return _internal_detections(index);
}
inline ::mergenvision::video::v1::FaceDetection* VideoObservationFrame::_internal_add_detections() {
  return _impl_.detections_.Add();
}
inline ::mergenvision::video::v1::FaceDetection* VideoObservationFrame::add_detections() {
  ::mergenvision::video::v1::FaceDetection* _add = _internal_add_detections();
  // @@protoc_insertion_point(field_add:mergenvision.video.v1.VideoObservationFrame.detections)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mergenvision::video::v1::FaceDetection >&
VideoObservationFrame::detections() const {
  // @@protoc_insertion_point(field_list:mergenvision.video.v1.VideoObservationFrame.detections)
  return _impl_.detections_;
}

// -------------------------------------------------------------------

// FaceDetection

// string detection_id = 1;
inline void FaceDetection::clear_detection_id() {
  _impl_.detection_id_.ClearToEmpty();
}
inline const std::string& FaceDetection::detection_id() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.detection_id)
  return _internal_detection_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FaceDetection::set_detection_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.detection_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.detection_id)
}
inline std::string* FaceDetection::mutable_detection_id() {
  std::string* _s = _internal_mutable_detection_id();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.FaceDetection.detection_id)
  return _s;
}
inline const std::string& FaceDetection::_internal_detection_id() const {
  return _impl_.detection_id_.Get();
}
inline void FaceDetection::_internal_set_detection_id(const std::string& value) {
  
  _impl_.detection_id_.Set(value, GetArenaForAllocation());
}
inline std::string* FaceDetection::_internal_mutable_detection_id() {
  
  return _impl_.detection_id_.Mutable(GetArenaForAllocation());
}
inline std::string* FaceDetection::release_detection_id() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.FaceDetection.detection_id)
  return _impl_.detection_id_.Release();
}
inline void FaceDetection::set_allocated_detection_id(std::string* detection_id) {
  if (detection_id != nullptr) {
    
  } else {
    
  }
  _impl_.detection_id_.SetAllocated(detection_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.detection_id_.IsDefault()) {
    _impl_.detection_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.FaceDetection.detection_id)
}

// int32 ordinal = 2;
inline void FaceDetection::clear_ordinal() {
  _impl_.ordinal_ = 0;
}
inline int32_t FaceDetection::_internal_ordinal() const {
  return _impl_.ordinal_;
}
inline int32_t FaceDetection::ordinal() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.ordinal)
  return _internal_ordinal();
}
inline void FaceDetection::_internal_set_ordinal(int32_t value) {
  
  _impl_.ordinal_ = value;
}
inline void FaceDetection::set_ordinal(int32_t value) {
  _internal_set_ordinal(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.ordinal)
}

// int32 x = 3;
inline void FaceDetection::clear_x() {
  _impl_.x_ = 0;
}
inline int32_t FaceDetection::_internal_x() const {
  return _impl_.x_;
}
inline int32_t FaceDetection::x() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.x)
  return _internal_x();
}
inline void FaceDetection::_internal_set_x(int32_t value) {
  
  _impl_.x_ = value;
}
inline void FaceDetection::set_x(int32_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.x)
}

// int32 y = 4;
inline void FaceDetection::clear_y() {
  _impl_.y_ = 0;
}
inline int32_t FaceDetection::_internal_y() const {
  return _impl_.y_;
}
inline int32_t FaceDetection::y() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.y)
  return _internal_y();
}
inline void FaceDetection::_internal_set_y(int32_t value) {
  
  _impl_.y_ = value;
}
inline void FaceDetection::set_y(int32_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.y)
}

// int32 width = 5;
inline void FaceDetection::clear_width() {
  _impl_.width_ = 0;
}
inline int32_t FaceDetection::_internal_width() const {
  return _impl_.width_;
}
inline int32_t FaceDetection::width() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.width)
  return _internal_width();
}
inline void FaceDetection::_internal_set_width(int32_t value) {
  
  _impl_.width_ = value;
}
inline void FaceDetection::set_width(int32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.width)
}

// int32 height = 6;
inline void FaceDetection::clear_height() {
  _impl_.height_ = 0;
}
inline int32_t FaceDetection::_internal_height() const {
  return _impl_.height_;
}
inline int32_t FaceDetection::height() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.height)
  return _internal_height();
}
inline void FaceDetection::_internal_set_height(int32_t value) {
  
  _impl_.height_ = value;
}
inline void FaceDetection::set_height(int32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.height)
}

// repeated float landmarks = 7;
inline int FaceDetection::_internal_landmarks_size() const {
  return _impl_.landmarks_.size();
}
inline int FaceDetection::landmarks_size() const {
  return _internal_landmarks_size();
}
inline void FaceDetection::clear_landmarks() {
  _impl_.landmarks_.Clear();
}
inline float FaceDetection::_internal_landmarks(int index) const {
  return _impl_.landmarks_.Get(index);
}
inline float FaceDetection::landmarks(int index) const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.landmarks)
  return _internal_landmarks(index);
}
inline void FaceDetection::set_landmarks(int index, float value) {
  _impl_.landmarks_.Set(index, value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.landmarks)
}
inline void FaceDetection::_internal_add_landmarks(float value) {
  _impl_.landmarks_.Add(value);
}
inline void FaceDetection::add_landmarks(float value) {
  _internal_add_landmarks(value);
  // @@protoc_insertion_point(field_add:mergenvision.video.v1.FaceDetection.landmarks)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
FaceDetection::_internal_landmarks() const {
  return _impl_.landmarks_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
FaceDetection::landmarks() const {
  // @@protoc_insertion_point(field_list:mergenvision.video.v1.FaceDetection.landmarks)
  return _internal_landmarks();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
FaceDetection::_internal_mutable_landmarks() {
  return &_impl_.landmarks_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
FaceDetection::mutable_landmarks() {
  // @@protoc_insertion_point(field_mutable_list:mergenvision.video.v1.FaceDetection.landmarks)
  return _internal_mutable_landmarks();
}

// float detector_score = 8;
inline void FaceDetection::clear_detector_score() {
  _impl_.detector_score_ = 0;
}
inline float FaceDetection::_internal_detector_score() const {
  return _impl_.detector_score_;
}
inline float FaceDetection::detector_score() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.detector_score)
  return _internal_detector_score();
}
inline void FaceDetection::_internal_set_detector_score(float value) {
  
  _impl_.detector_score_ = value;
}
inline void FaceDetection::set_detector_score(float value) {
  _internal_set_detector_score(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.detector_score)
}

// float quality_score = 9;
inline void FaceDetection::clear_quality_score() {
  _impl_.quality_score_ = 0;
}
inline float FaceDetection::_internal_quality_score() const {
  return _impl_.quality_score_;
}
inline float FaceDetection::quality_score() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.quality_score)
  return _internal_quality_score();
}
inline void FaceDetection::_internal_set_quality_score(float value) {
  
  _impl_.quality_score_ = value;
}
inline void FaceDetection::set_quality_score(float value) {
  _internal_set_quality_score(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.quality_score)
}

// bool tracking_eligible = 10;
inline void FaceDetection::clear_tracking_eligible() {
  _impl_.tracking_eligible_ = false;
}
inline bool FaceDetection::_internal_tracking_eligible() const {
  return _impl_.tracking_eligible_;
}
inline bool FaceDetection::tracking_eligible() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.tracking_eligible)
  return _internal_tracking_eligible();
}
inline void FaceDetection::_internal_set_tracking_eligible(bool value) {
  
  _impl_.tracking_eligible_ = value;
}
inline void FaceDetection::set_tracking_eligible(bool value) {
  _internal_set_tracking_eligible(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.tracking_eligible)
}

// bool recognition_eligible = 11;
inline void FaceDetection::clear_recognition_eligible() {
  _impl_.recognition_eligible_ = false;
}
inline bool FaceDetection::_internal_recognition_eligible() const {
  return _impl_.recognition_eligible_;
}
inline bool FaceDetection::recognition_eligible() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.recognition_eligible)
  return _internal_recognition_eligible();
}
inline void FaceDetection::_internal_set_recognition_eligible(bool value) {
  
  _impl_.recognition_eligible_ = value;
}
inline void FaceDetection::set_recognition_eligible(bool value) {
  _internal_set_recognition_eligible(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.recognition_eligible)
}

// string rejection_code = 12;
inline void FaceDetection::clear_rejection_code() {
  _impl_.rejection_code_.ClearToEmpty();
}
inline const std::string& FaceDetection::rejection_code() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.rejection_code)
  return _internal_rejection_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FaceDetection::set_rejection_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.rejection_code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.rejection_code)
}
inline std::string* FaceDetection::mutable_rejection_code() {
  std::string* _s = _internal_mutable_rejection_code();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.FaceDetection.rejection_code)
  return _s;
}
inline const std::string& FaceDetection::_internal_rejection_code() const {
  return _impl_.rejection_code_.Get();
}
inline void FaceDetection::_internal_set_rejection_code(const std::string& value) {
  
  _impl_.rejection_code_.Set(value, GetArenaForAllocation());
}
inline std::string* FaceDetection::_internal_mutable_rejection_code() {
  
  return _impl_.rejection_code_.Mutable(GetArenaForAllocation());
}
inline std::string* FaceDetection::release_rejection_code() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.FaceDetection.rejection_code)
  return _impl_.rejection_code_.Release();
}
inline void FaceDetection::set_allocated_rejection_code(std::string* rejection_code) {
  if (rejection_code != nullptr) {
    
  } else {
    
  }
  _impl_.rejection_code_.SetAllocated(rejection_code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.rejection_code_.IsDefault()) {
    _impl_.rejection_code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.FaceDetection.rejection_code)
}

// repeated float embedding = 13;
inline int FaceDetection::_internal_embedding_size() const {
  return _impl_.embedding_.size();
}
inline int FaceDetection::embedding_size() const {
  return _internal_embedding_size();
}
inline void FaceDetection::clear_embedding() {
  _impl_.embedding_.Clear();
}
inline float FaceDetection::_internal_embedding(int index) const {
  return _impl_.embedding_.Get(index);
}
inline float FaceDetection::embedding(int index) const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.embedding)
  return _internal_embedding(index);
}
inline void FaceDetection::set_embedding(int index, float value) {
  _impl_.embedding_.Set(index, value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.embedding)
}
inline void FaceDetection::_internal_add_embedding(float value) {
  _impl_.embedding_.Add(value);
}
inline void FaceDetection::add_embedding(float value) {
  _internal_add_embedding(value);
  // @@protoc_insertion_point(field_add:mergenvision.video.v1.FaceDetection.embedding)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
FaceDetection::_internal_embedding() const {
  return _impl_.embedding_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
FaceDetection::embedding() const {
  // @@protoc_insertion_point(field_list:mergenvision.video.v1.FaceDetection.embedding)
  return _internal_embedding();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
FaceDetection::_internal_mutable_embedding() {
  return &_impl_.embedding_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
FaceDetection::mutable_embedding() {
  // @@protoc_insertion_point(field_mutable_list:mergenvision.video.v1.FaceDetection.embedding)
  return _internal_mutable_embedding();
}

// string model_version = 14;
inline void FaceDetection::clear_model_version() {
  _impl_.model_version_.ClearToEmpty();
}
inline const std::string& FaceDetection::model_version() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.model_version)
  return _internal_model_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FaceDetection::set_model_version(ArgT0&& arg0, ArgT... args) {
 
 _impl_.model_version_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.model_version)
}
inline std::string* FaceDetection::mutable_model_version() {
  std::string* _s = _internal_mutable_model_version();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.FaceDetection.model_version)
  return _s;
}
inline const std::string& FaceDetection::_internal_model_version() const {
  return _impl_.model_version_.Get();
}
inline void FaceDetection::_internal_set_model_version(const std::string& value) {
  
  _impl_.model_version_.Set(value, GetArenaForAllocation());
}
inline std::string* FaceDetection::_internal_mutable_model_version() {
  
  return _impl_.model_version_.Mutable(GetArenaForAllocation());
}
inline std::string* FaceDetection::release_model_version() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.FaceDetection.model_version)
  return _impl_.model_version_.Release();
}
inline void FaceDetection::set_allocated_model_version(std::string* model_version) {
  if (model_version != nullptr) {
    
  } else {
    
  }
  _impl_.model_version_.SetAllocated(model_version, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.model_version_.IsDefault()) {
    _impl_.model_version_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.FaceDetection.model_version)
}

// string preprocess_version = 15;
inline void FaceDetection::clear_preprocess_version() {
  _impl_.preprocess_version_.ClearToEmpty();
}
inline const std::string& FaceDetection::preprocess_version() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.preprocess_version)
  return _internal_preprocess_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FaceDetection::set_preprocess_version(ArgT0&& arg0, ArgT... args) {
 
 _impl_.preprocess_version_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.preprocess_version)
}
inline std::string* FaceDetection::mutable_preprocess_version() {
  std::string* _s = _internal_mutable_preprocess_version();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.FaceDetection.preprocess_version)
  return _s;
}
inline const std::string& FaceDetection::_internal_preprocess_version() const {
  return _impl_.preprocess_version_.Get();
}
inline void FaceDetection::_internal_set_preprocess_version(const std::string& value) {
  
  _impl_.preprocess_version_.Set(value, GetArenaForAllocation());
}
inline std::string* FaceDetection::_internal_mutable_preprocess_version() {
  
  return _impl_.preprocess_version_.Mutable(GetArenaForAllocation());
}
inline std::string* FaceDetection::release_preprocess_version() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.FaceDetection.preprocess_version)
  return _impl_.preprocess_version_.Release();
}
inline void FaceDetection::set_allocated_preprocess_version(std::string* preprocess_version) {
  if (preprocess_version != nullptr) {
    
  } else {
    
  }
  _impl_.preprocess_version_.SetAllocated(preprocess_version, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.preprocess_version_.IsDefault()) {
    _impl_.preprocess_version_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.FaceDetection.preprocess_version)
}

// string raw_track_key = 16;
inline void FaceDetection::clear_raw_track_key() {
  _impl_.raw_track_key_.ClearToEmpty();
}
inline const std::string& FaceDetection::raw_track_key() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.FaceDetection.raw_track_key)
  return _internal_raw_track_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FaceDetection::set_raw_track_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.raw_track_key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.FaceDetection.raw_track_key)
}
inline std::string* FaceDetection::mutable_raw_track_key() {
  std::string* _s = _internal_mutable_raw_track_key();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.FaceDetection.raw_track_key)
  return _s;
}
inline const std::string& FaceDetection::_internal_raw_track_key() const {
  return _impl_.raw_track_key_.Get();
}
inline void FaceDetection::_internal_set_raw_track_key(const std::string& value) {
  
  _impl_.raw_track_key_.Set(value, GetArenaForAllocation());
}
inline std::string* FaceDetection::_internal_mutable_raw_track_key() {
  
  return _impl_.raw_track_key_.Mutable(GetArenaForAllocation());
}
inline std::string* FaceDetection::release_raw_track_key() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.FaceDetection.raw_track_key)
  return _impl_.raw_track_key_.Release();
}
inline void FaceDetection::set_allocated_raw_track_key(std::string* raw_track_key) {
  if (raw_track_key != nullptr) {
    
  } else {
    
  }
  _impl_.raw_track_key_.SetAllocated(raw_track_key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.raw_track_key_.IsDefault()) {
    _impl_.raw_track_key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.FaceDetection.raw_track_key)
}

// -------------------------------------------------------------------

// ObservationChunkFooter

// string job_id = 1;
inline void ObservationChunkFooter::clear_job_id() {
  _impl_.job_id_.ClearToEmpty();
}
inline const std::string& ObservationChunkFooter::job_id() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.ObservationChunkFooter.job_id)
  return _internal_job_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ObservationChunkFooter::set_job_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.job_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.ObservationChunkFooter.job_id)
}
inline std::string* ObservationChunkFooter::mutable_job_id() {
  std::string* _s = _internal_mutable_job_id();
  // @@protoc_insertion_point(field_mutable:mergenvision.video.v1.ObservationChunkFooter.job_id)
  return _s;
}
inline const std::string& ObservationChunkFooter::_internal_job_id() const {
  return _impl_.job_id_.Get();
}
inline void ObservationChunkFooter::_internal_set_job_id(const std::string& value) {
  
  _impl_.job_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ObservationChunkFooter::_internal_mutable_job_id() {
  
  return _impl_.job_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ObservationChunkFooter::release_job_id() {
  // @@protoc_insertion_point(field_release:mergenvision.video.v1.ObservationChunkFooter.job_id)
  return _impl_.job_id_.Release();
}
inline void ObservationChunkFooter::set_allocated_job_id(std::string* job_id) {
  if (job_id != nullptr) {
    
  } else {
    
  }
  _impl_.job_id_.SetAllocated(job_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.job_id_.IsDefault()) {
    _impl_.job_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mergenvision.video.v1.ObservationChunkFooter.job_id)
}

// int64 sequence_no = 2;
inline void ObservationChunkFooter::clear_sequence_no() {
  _impl_.sequence_no_ = int64_t{0};
}
inline int64_t ObservationChunkFooter::_internal_sequence_no() const {
  return _impl_.sequence_no_;
}
inline int64_t ObservationChunkFooter::sequence_no() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.ObservationChunkFooter.sequence_no)
  return _internal_sequence_no();
}
inline void ObservationChunkFooter::_internal_set_sequence_no(int64_t value) {
  
  _impl_.sequence_no_ = value;
}
inline void ObservationChunkFooter::set_sequence_no(int64_t value) {
  _internal_set_sequence_no(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.ObservationChunkFooter.sequence_no)
}

// int64 frame_count = 3;
inline void ObservationChunkFooter::clear_frame_count() {
  _impl_.frame_count_ = int64_t{0};
}
inline int64_t ObservationChunkFooter::_internal_frame_count() const {
  return _impl_.frame_count_;
}
inline int64_t ObservationChunkFooter::frame_count() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.ObservationChunkFooter.frame_count)
  return _internal_frame_count();
}
inline void ObservationChunkFooter::_internal_set_frame_count(int64_t value) {
  
  _impl_.frame_count_ = value;
}
inline void ObservationChunkFooter::set_frame_count(int64_t value) {
  _internal_set_frame_count(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.ObservationChunkFooter.frame_count)
}

// int64 sha256_prefix = 4;
inline void ObservationChunkFooter::clear_sha256_prefix() {
  _impl_.sha256_prefix_ = int64_t{0};
}
inline int64_t ObservationChunkFooter::_internal_sha256_prefix() const {
  return _impl_.sha256_prefix_;
}
inline int64_t ObservationChunkFooter::sha256_prefix() const {
  // @@protoc_insertion_point(field_get:mergenvision.video.v1.ObservationChunkFooter.sha256_prefix)
  return _internal_sha256_prefix();
}
inline void ObservationChunkFooter::_internal_set_sha256_prefix(int64_t value) {
  
  _impl_.sha256_prefix_ = value;
}
inline void ObservationChunkFooter::set_sha256_prefix(int64_t value) {
  _internal_set_sha256_prefix(value);
  // @@protoc_insertion_point(field_set:mergenvision.video.v1.ObservationChunkFooter.sha256_prefix)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace video
}  // namespace mergenvision

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_video_5fobservation_5fv1_2eproto
