# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_track_template_v1.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'video_track_template_v1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dvideo_track_template_v1.proto\x12\x15mergenvision.video.v1\"\xd3\x01\n\x13TrackTemplateBundle\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x10\n\x08video_id\x18\x02 \x01(\t\x12\x13\n\x0bsequence_no\x18\x03 \x01(\x03\x12\x15\n\rmodel_version\x18\x04 \x01(\t\x12\x1a\n\x12preprocess_version\x18\x05 \x01(\t\x12\x16\n\x0e\x63onfig_version\x18\x06 \x01(\t\x12:\n\ttemplates\x18\x07 \x03(\x0b\x32\'.mergenvision.video.v1.RawTrackTemplate\"\xbb\x03\n\x10RawTrackTemplate\x12\x15\n\rraw_track_key\x18\x01 \x01(\t\x12\x14\n\x0c\x66irst_pts_ns\x18\x02 \x01(\x03\x12\x13\n\x0blast_pts_ns\x18\x03 \x01(\x03\x12\x19\n\x11observation_count\x18\x04 \x01(\x03\x12\"\n\x1a\x65ligible_observation_count\x18\x05 \x01(\x03\x12\x1a\n\x12template_embedding\x18\x06 \x03(\x02\x12\x18\n\x10template_quality\x18\x07 \x01(\x02\x12(\n representative_crop_relative_key\x18\x08 \x01(\t\x12\x18\n\x10representative_x\x18\t \x01(\x05\x12\x18\n\x10representative_y\x18\n \x01(\x05\x12\x1c\n\x14representative_width\x18\x0b \x01(\x05\x12\x1d\n\x15representative_height\x18\x0c \x01(\x05\x12\x1d\n\x15representative_pts_ns\x18\r \x01(\x03\x12\x1e\n\x16representative_ordinal\x18\x0e \x01(\x05\x12\x16\n\x0eno_crop_reason\x18\x0f \x01(\t\"R\n\x13TrackTemplateFooter\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x13\n\x0bsequence_no\x18\x02 \x01(\x03\x12\x16\n\x0etemplate_count\x18\x03 \x01(\x03\x42\x34Z2github.com/mergenvision/backend/contracts/video/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_track_template_v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/mergenvision/backend/contracts/video/v1'
  _globals['_TRACKTEMPLATEBUNDLE']._serialized_start=57
  _globals['_TRACKTEMPLATEBUNDLE']._serialized_end=268
  _globals['_RAWTRACKTEMPLATE']._serialized_start=271
  _globals['_RAWTRACKTEMPLATE']._serialized_end=714
  _globals['_TRACKTEMPLATEFOOTER']._serialized_start=716
  _globals['_TRACKTEMPLATEFOOTER']._serialized_end=798
# @@protoc_insertion_point(module_scope)
