# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_observation_v1.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'video_observation_v1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1avideo_observation_v1.proto\x12\x15mergenvision.video.v1\"\xb1\x02\n\x15VideoObservationFrame\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x10\n\x08video_id\x18\x02 \x01(\t\x12\x14\n\x0cstream_index\x18\x03 \x01(\x05\x12\x13\n\x0b\x66rame_index\x18\x04 \x01(\x03\x12\x12\n\nsource_pts\x18\x05 \x01(\x03\x12\x15\n\rtime_base_num\x18\x06 \x01(\x03\x12\x15\n\rtime_base_den\x18\x07 \x01(\x03\x12\x0e\n\x06pts_ns\x18\x08 \x01(\x03\x12\x15\n\rdisplay_width\x18\t \x01(\x05\x12\x16\n\x0e\x64isplay_height\x18\n \x01(\x05\x12\x10\n\x08rotation\x18\x0b \x01(\x05\x12\x38\n\ndetections\x18\x0c \x03(\x0b\x32$.mergenvision.video.v1.FaceDetection\"\xdb\x02\n\rFaceDetection\x12\x14\n\x0c\x64\x65tection_id\x18\x01 \x01(\t\x12\x0f\n\x07ordinal\x18\x02 \x01(\x05\x12\t\n\x01x\x18\x03 \x01(\x05\x12\t\n\x01y\x18\x04 \x01(\x05\x12\r\n\x05width\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05\x12\x11\n\tlandmarks\x18\x07 \x03(\x02\x12\x16\n\x0e\x64\x65tector_score\x18\x08 \x01(\x02\x12\x15\n\rquality_score\x18\t \x01(\x02\x12\x19\n\x11tracking_eligible\x18\n \x01(\x08\x12\x1c\n\x14recognition_eligible\x18\x0b \x01(\x08\x12\x16\n\x0erejection_code\x18\x0c \x01(\t\x12\x11\n\tembedding\x18\r \x03(\x02\x12\x15\n\rmodel_version\x18\x0e \x01(\t\x12\x1a\n\x12preprocess_version\x18\x0f \x01(\t\x12\x15\n\rraw_track_key\x18\x10 \x01(\t\"i\n\x16ObservationChunkFooter\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x13\n\x0bsequence_no\x18\x02 \x01(\x03\x12\x13\n\x0b\x66rame_count\x18\x03 \x01(\x03\x12\x15\n\rsha256_prefix\x18\x04 \x01(\x03\x42\x34Z2github.com/mergenvision/backend/contracts/video/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_observation_v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/mergenvision/backend/contracts/video/v1'
  _globals['_VIDEOOBSERVATIONFRAME']._serialized_start=54
  _globals['_VIDEOOBSERVATIONFRAME']._serialized_end=359
  _globals['_FACEDETECTION']._serialized_start=362
  _globals['_FACEDETECTION']._serialized_end=709
  _globals['_OBSERVATIONCHUNKFOOTER']._serialized_start=711
  _globals['_OBSERVATIONCHUNKFOOTER']._serialized_end=816
# @@protoc_insertion_point(module_scope)
